//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ada_tb
    {
        public string ada01 { get; set; }
        public string ada02 { get; set; }
        public string ada03 { get; set; }
        public string ada04 { get; set; }
        public string ada05 { get; set; }
        public string ada06 { get; set; }
        public string ada07 { get; set; }
        public string ada08 { get; set; }
        public string ada09 { get; set; }
        public string ada10 { get; set; }
        public string adacreu { get; set; }
        public string adacreg { get; set; }
        public Nullable<System.DateTime> adacred { get; set; }
        public string adamodu { get; set; }
        public string adamodg { get; set; }
        public Nullable<System.DateTime> adamodd { get; set; }
        public string adasecu { get; set; }
        public string adasecg { get; set; }
    }
}
