//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class adc_tb
    {
        public string adc01 { get; set; }
        public string adc02 { get; set; }
        public string adc03 { get; set; }
        public string adc04 { get; set; }
        public string adc05 { get; set; }
        public string adccreu { get; set; }
        public string adccreg { get; set; }
        public Nullable<System.DateTime> adccred { get; set; }
        public string adcmodu { get; set; }
        public string adcmodg { get; set; }
        public Nullable<System.DateTime> adcmodd { get; set; }
        public string adcsecu { get; set; }
        public string adcsecg { get; set; }
    }
}
