//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ado_tb
    {
        public string ado01 { get; set; }
        public string ado02 { get; set; }
        public string ado03 { get; set; }
        public string ado04 { get; set; }
        public string ado05 { get; set; }
        public string ado06 { get; set; }
        public string ado07 { get; set; }
        public string ado08 { get; set; }
        public string ado09 { get; set; }
        public string ado10 { get; set; }
        public Nullable<decimal> ado11 { get; set; }
        public string ado12 { get; set; }
        public string ado13 { get; set; }
        public string ado14 { get; set; }
        public string ado15 { get; set; }
        public string ado16 { get; set; }
        public string ado17 { get; set; }
        public string ado18 { get; set; }
        public string ado19 { get; set; }
        public string ado20 { get; set; }
        public string ado21 { get; set; }
        public string ado22 { get; set; }
        public string ado23 { get; set; }
        public string ado24 { get; set; }
        public string ado25 { get; set; }
        public string adocreu { get; set; }
        public string adocreg { get; set; }
        public Nullable<System.DateTime> adocred { get; set; }
        public string adomodu { get; set; }
        public string adomodg { get; set; }
        public Nullable<System.DateTime> adomodd { get; set; }
        public string adosecu { get; set; }
        public string adosecg { get; set; }
    }
}
