//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ady_tb
    {
        public string ady01 { get; set; }
        public int ady02 { get; set; }
        public string ady03 { get; set; }
        public int ady04 { get; set; }
        public int ady05 { get; set; }
        public int ady06 { get; set; }
        public int ady07 { get; set; }
        public string ady08 { get; set; }
        public string ady09 { get; set; }
        public string ady10 { get; set; }
        public string adycreu { get; set; }
        public string adycreg { get; set; }
        public Nullable<System.DateTime> adycred { get; set; }
        public string adymodu { get; set; }
        public string adymodg { get; set; }
        public Nullable<System.DateTime> adymodd { get; set; }
    }
}
