//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ata_tb
    {
        public string ata01 { get; set; }
        public string ata02 { get; set; }
        public string ata03 { get; set; }
        public string ata04 { get; set; }
        public string ata05 { get; set; }
        public string ata06 { get; set; }
        public string ata07 { get; set; }
        public string ata08 { get; set; }
        public string ata09 { get; set; }
        public string ata10 { get; set; }
        public string atacreu { get; set; }
        public string atacreg { get; set; }
        public Nullable<System.DateTime> atacred { get; set; }
        public string atamodu { get; set; }
        public string atamodg { get; set; }
        public Nullable<System.DateTime> atamodd { get; set; }
        public string atasecu { get; set; }
        public string atasecg { get; set; }
    }
}
