//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class atb_tb
    {
        public string atb01 { get; set; }
        public string atb02 { get; set; }
        public string atb03 { get; set; }
        public string atb04 { get; set; }
        public string atb05 { get; set; }
        public string atbcreu { get; set; }
        public string atbcreg { get; set; }
        public Nullable<System.DateTime> atbcred { get; set; }
        public string atbmodu { get; set; }
        public string atbmodg { get; set; }
        public Nullable<System.DateTime> atbmodd { get; set; }
        public string atbsecu { get; set; }
        public string atbsecg { get; set; }
    }
}
