//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class azf_tb
    {
        public string azf01 { get; set; }
        public string azf02 { get; set; }
        public string azf03 { get; set; }
        public string azf04 { get; set; }
        public string azf05 { get; set; }
        public string azf06 { get; set; }
        public string azf07 { get; set; }
        public string azf08 { get; set; }
        public string azfcreu { get; set; }
        public string azfcreg { get; set; }
        public Nullable<System.DateTime> azfcred { get; set; }
        public string azfmodu { get; set; }
        public string azfmodg { get; set; }
        public Nullable<System.DateTime> azfmodd { get; set; }
    }
}
