//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class azp_tb
    {
        public string azp01 { get; set; }
        public string azp02 { get; set; }
        public string azp03 { get; set; }
        public string azp04 { get; set; }
        public string azp05 { get; set; }
        public string azp06 { get; set; }
        public string azp07 { get; set; }
        public string azp08 { get; set; }
        public string azp09 { get; set; }
        public string azp10 { get; set; }
        public string azp11 { get; set; }
        public string azp12 { get; set; }
        public string azpcreu { get; set; }
        public string azpcreg { get; set; }
        public Nullable<System.DateTime> azpcred { get; set; }
        public string azpmodu { get; set; }
        public string azpmodg { get; set; }
        public Nullable<System.DateTime> azpmodd { get; set; }
        public string azpsecu { get; set; }
        public string azpsecg { get; set; }
    }
}
