//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bea_tb
    {
        public string beacomp { get; set; }
        public string bea01 { get; set; }
        public string bea02 { get; set; }
        public string bea03 { get; set; }
        public string bea04 { get; set; }
        public string bea05 { get; set; }
        public string bea06 { get; set; }
        public string bea07 { get; set; }
        public string bea08 { get; set; }
        public string bea09 { get; set; }
        public string bea10 { get; set; }
        public string bea11 { get; set; }
        public string bea12 { get; set; }
        public string bea13 { get; set; }
        public string bea14 { get; set; }
        public string bea15 { get; set; }
        public string beacreu { get; set; }
        public string beacreg { get; set; }
        public Nullable<System.DateTime> beacred { get; set; }
        public string beamodu { get; set; }
        public string beamodg { get; set; }
        public Nullable<System.DateTime> beamodd { get; set; }
        public string beasecu { get; set; }
        public string beasecg { get; set; }
    }
}
