//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class beb_tb
    {
        public string beb01 { get; set; }
        public string beb02 { get; set; }
        public string beb03 { get; set; }
        public string beb04 { get; set; }
        public string beb05 { get; set; }
        public string beb06 { get; set; }
        public string beb07 { get; set; }
        public string beb08 { get; set; }
        public string bebvali { get; set; }
        public string bebcreu { get; set; }
        public string bebcreg { get; set; }
        public Nullable<System.DateTime> bebcred { get; set; }
        public string bebmodu { get; set; }
        public string bebmodg { get; set; }
        public Nullable<System.DateTime> bebmodd { get; set; }
        public string bebsecu { get; set; }
        public string bebsecg { get; set; }
    }
}
