//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_tb
    {
        public string bec01 { get; set; }
        public string bec02 { get; set; }
        public string bec03 { get; set; }
        public string bec04 { get; set; }
        public string bec05 { get; set; }
        public string bec06 { get; set; }
        public string bec07 { get; set; }
        public string bec08 { get; set; }
        public string bec09 { get; set; }
        public string bec10 { get; set; }
        public string bec11 { get; set; }
        public string bec12 { get; set; }
        public string bec13 { get; set; }
        public string becvali { get; set; }
        public string beccreu { get; set; }
        public string beccreg { get; set; }
        public Nullable<System.DateTime> beccred { get; set; }
        public string becmodu { get; set; }
        public string becmodg { get; set; }
        public Nullable<System.DateTime> becmodd { get; set; }
        public string becsecu { get; set; }
        public string becsecg { get; set; }
    }
}
