//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bej_tb
    {
        public string bej01 { get; set; }
        public string bej02 { get; set; }
        public decimal bej03 { get; set; }
        public string bej04 { get; set; }
        public string bej05 { get; set; }
        public string bejvali { get; set; }
        public string bejcreu { get; set; }
        public string bejcreg { get; set; }
        public Nullable<System.DateTime> bejcred { get; set; }
        public string bejmodu { get; set; }
        public string bejmodg { get; set; }
        public Nullable<System.DateTime> bejmodd { get; set; }
        public string bejsecu { get; set; }
        public string bejsecg { get; set; }
    }
}
