//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bek_tb
    {
        public string bek01 { get; set; }
        public string bek02 { get; set; }
        public decimal bek03 { get; set; }
        public decimal bek04 { get; set; }
        public string bek05 { get; set; }
        public string bek06 { get; set; }
        public string bekvali { get; set; }
        public string bekcreu { get; set; }
        public string bekcreg { get; set; }
        public Nullable<System.DateTime> bekcred { get; set; }
        public string bekmodu { get; set; }
        public string bekmodg { get; set; }
        public Nullable<System.DateTime> bekmodd { get; set; }
        public string beksecu { get; set; }
        public string beksecg { get; set; }
    }
}
