//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgb_tb
    {
        public string bgb01 { get; set; }
        public decimal bgb02 { get; set; }
        public string bgb03 { get; set; }
        public Nullable<decimal> bgb04 { get; set; }
        public string bgb05 { get; set; }
        public string bgb06 { get; set; }
        public string bgb07 { get; set; }
        public string bgb08 { get; set; }
        public string bgb09 { get; set; }
        public string bgb10 { get; set; }
        public string bgbcreu { get; set; }
        public string bgbcreg { get; set; }
        public Nullable<System.DateTime> bgbcred { get; set; }
        public string bgbmodu { get; set; }
        public string bgbmodg { get; set; }
        public Nullable<System.DateTime> bgbmodd { get; set; }
    }
}
