//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cea_tb
    {
        public string cea00 { get; set; }
        public string cea01 { get; set; }
        public Nullable<System.DateTime> cea02 { get; set; }
        public string cea03 { get; set; }
        public string cea04 { get; set; }
        public string cea05 { get; set; }
        public string cea06 { get; set; }
        public decimal cea07 { get; set; }
        public string cea08 { get; set; }
        public string cea09 { get; set; }
        public string cea10 { get; set; }
        public string cea11 { get; set; }
        public decimal cea12 { get; set; }
        public decimal cea13 { get; set; }
        public decimal cea13t { get; set; }
        public decimal cea13g { get; set; }
        public decimal cea14 { get; set; }
        public decimal cea15 { get; set; }
        public decimal cea15t { get; set; }
        public decimal cea15g { get; set; }
        public decimal cea16 { get; set; }
        public string cea17 { get; set; }
        public string cea18 { get; set; }
        public Nullable<System.DateTime> cea19 { get; set; }
        public Nullable<System.DateTime> cea20 { get; set; }
        public string cea21 { get; set; }
        public string cea22 { get; set; }
        public string cea23 { get; set; }
        public Nullable<System.DateTime> cea24 { get; set; }
        public string cea25 { get; set; }
        public string cea26 { get; set; }
        public string cea27 { get; set; }
        public string cea28 { get; set; }
        public string cea29 { get; set; }
        public string cea30 { get; set; }
        public string cea31 { get; set; }
        public string cea32 { get; set; }
        public string cea33 { get; set; }
        public string cea34 { get; set; }
        public string cea35 { get; set; }
        public string cea36 { get; set; }
        public string cea37 { get; set; }
        public string cea38 { get; set; }
        public string cea39 { get; set; }
        public string cea40 { get; set; }
        public string ceaconf { get; set; }
        public Nullable<System.DateTime> ceacond { get; set; }
        public string ceaconu { get; set; }
        public string ceastat { get; set; }
        public string ceacomp { get; set; }
        public string ceacreu { get; set; }
        public string ceacreg { get; set; }
        public Nullable<System.DateTime> ceacred { get; set; }
        public string ceamodu { get; set; }
        public string ceamodg { get; set; }
        public Nullable<System.DateTime> ceamodd { get; set; }
        public string ceasecu { get; set; }
        public string ceasecg { get; set; }
    }
}
