//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ceb_tb
    {
        public string ceb00 { get; set; }
        public string ceb01 { get; set; }
        public decimal ceb02 { get; set; }
        public string ceb03 { get; set; }
        public string ceb04 { get; set; }
        public decimal ceb05 { get; set; }
        public decimal ceb06 { get; set; }
        public decimal ceb07 { get; set; }
        public decimal ceb07t { get; set; }
        public decimal ceb08 { get; set; }
        public decimal ceb09 { get; set; }
        public decimal ceb09t { get; set; }
        public string ceb10 { get; set; }
        public string ceb11 { get; set; }
        public Nullable<decimal> ceb12 { get; set; }
        public decimal ceb13 { get; set; }
        public decimal ceb14 { get; set; }
        public decimal ceb15 { get; set; }
        public string ceb16 { get; set; }
        public string ceb17 { get; set; }
        public string ceb18 { get; set; }
        public string ceb19 { get; set; }
        public string ceb20 { get; set; }
        public string ceb21 { get; set; }
        public string ceb22 { get; set; }
        public string ceb23 { get; set; }
        public string cebcomp { get; set; }
        public string cebcreu { get; set; }
        public string cebcreg { get; set; }
        public Nullable<System.DateTime> cebcred { get; set; }
        public string cebmodu { get; set; }
        public string cebmodg { get; set; }
        public Nullable<System.DateTime> cebmodd { get; set; }
    }
}
