//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cef_tb
    {
        public string cef01 { get; set; }
        public string cef02 { get; set; }
        public string cef03 { get; set; }
        public string cefcomp { get; set; }
        public string cefcreu { get; set; }
        public string cefcreg { get; set; }
        public Nullable<System.DateTime> cefcred { get; set; }
        public string cefmodu { get; set; }
        public string cefmodg { get; set; }
        public Nullable<System.DateTime> cefmodd { get; set; }
    }
}
