//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfa_tb
    {
        public string cfa01 { get; set; }
        public Nullable<System.DateTime> cfa02 { get; set; }
        public string cfa03 { get; set; }
        public string cfa04 { get; set; }
        public string cfa05 { get; set; }
        public string cfa06 { get; set; }
        public string cfa07 { get; set; }
        public decimal cfa08 { get; set; }
        public decimal cfa09 { get; set; }
        public decimal cfa10 { get; set; }
        public decimal cfa11 { get; set; }
        public string cfa12 { get; set; }
        public string cfa13 { get; set; }
        public string cfa14 { get; set; }
        public string cfa15 { get; set; }
        public string cfa16 { get; set; }
        public string cfa17 { get; set; }
        public string cfa18 { get; set; }
        public string cfa19 { get; set; }
        public string cfa20 { get; set; }
        public string cfa21 { get; set; }
        public string cfa22 { get; set; }
        public string cfa23 { get; set; }
        public string cfa24 { get; set; }
        public string cfa25 { get; set; }
        public decimal cfaprno { get; set; }
        public string cfaconf { get; set; }
        public Nullable<System.DateTime> cfacond { get; set; }
        public string cfaconu { get; set; }
        public string cfastat { get; set; }
        public string cfacomp { get; set; }
        public string cfacreu { get; set; }
        public string cfacreg { get; set; }
        public Nullable<System.DateTime> cfacred { get; set; }
        public string cfamodu { get; set; }
        public string cfamodg { get; set; }
        public Nullable<System.DateTime> cfamodd { get; set; }
        public string cfasecu { get; set; }
        public string cfasecg { get; set; }
    }
}
