//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfb_tb
    {
        public string cfb01 { get; set; }
        public decimal cfb02 { get; set; }
        public string cfb03 { get; set; }
        public string cfb04 { get; set; }
        public string cfb05 { get; set; }
        public Nullable<decimal> cfb06 { get; set; }
        public string cfb07 { get; set; }
        public decimal cfb08 { get; set; }
        public decimal cfb09 { get; set; }
        public decimal cfb10 { get; set; }
        public string cfb11 { get; set; }
        public string cfb12 { get; set; }
        public string cfb13 { get; set; }
        public string cfb14 { get; set; }
        public string cfb15 { get; set; }
        public string cfb16 { get; set; }
        public string cfb17 { get; set; }
        public string cfb18 { get; set; }
        public string cfb19 { get; set; }
        public string cfb20 { get; set; }
        public string cfb21 { get; set; }
        public string cfb22 { get; set; }
        public string cfb23 { get; set; }
        public string cfb24 { get; set; }
        public string cfb25 { get; set; }
        public string cfbcomp { get; set; }
        public string cfbcreu { get; set; }
        public string cfbcreg { get; set; }
        public Nullable<System.DateTime> cfbcred { get; set; }
        public string cfbmodu { get; set; }
        public string cfbmodg { get; set; }
        public Nullable<System.DateTime> cfbmodd { get; set; }
    }
}
