//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gbj_tb
    {
        public string gbj01 { get; set; }
        public string gbj02 { get; set; }
        public decimal gbj03 { get; set; }
        public decimal gbj04 { get; set; }
        public decimal gbj05 { get; set; }
        public decimal gbj06 { get; set; }
        public decimal gbj07 { get; set; }
        public decimal gbj08 { get; set; }
        public string gbjcomp { get; set; }
    }
}
