//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gea_tb
    {
        public string gea01 { get; set; }
        public string gea02 { get; set; }
        public decimal gea03 { get; set; }
        public decimal gea04 { get; set; }
        public Nullable<System.DateTime> gea05 { get; set; }
        public string gea06 { get; set; }
        public Nullable<System.DateTime> gea07 { get; set; }
        public decimal gea08 { get; set; }
        public decimal gea09 { get; set; }
        public string gea10 { get; set; }
        public string gea11 { get; set; }
        public string gea12 { get; set; }
        public decimal geaprno { get; set; }
        public string geacomp { get; set; }
        public string geacreu { get; set; }
        public string geacreg { get; set; }
        public Nullable<System.DateTime> geacred { get; set; }
        public string geamodu { get; set; }
        public string geamodg { get; set; }
        public Nullable<System.DateTime> geamodd { get; set; }
        public string geasecu { get; set; }
        public string geasecg { get; set; }
    }
}
