//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class geb_tb
    {
        public string geb01 { get; set; }
        public string geb02 { get; set; }
        public decimal geb03 { get; set; }
        public decimal geb04 { get; set; }
        public decimal geb05 { get; set; }
        public string geb06 { get; set; }
        public string geb07 { get; set; }
        public string geb08 { get; set; }
        public string geb09 { get; set; }
        public decimal geb10 { get; set; }
        public string geb11 { get; set; }
        public decimal geb12 { get; set; }
        public decimal geb13 { get; set; }
        public string geb14 { get; set; }
        public string geb15 { get; set; }
        public string geb16 { get; set; }
        public string geb17 { get; set; }
        public string geb18 { get; set; }
        public string geb19 { get; set; }
        public string geb20 { get; set; }
        public string geb21 { get; set; }
        public string gebcomp { get; set; }
        public string gebcreu { get; set; }
        public string gebcreg { get; set; }
        public Nullable<System.DateTime> gebcred { get; set; }
        public string gebmodu { get; set; }
        public string gebmodg { get; set; }
        public Nullable<System.DateTime> gebmodd { get; set; }
    }
}
