//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gfa_tb
    {
        public string gfa01 { get; set; }
        public Nullable<System.DateTime> gfa02 { get; set; }
        public decimal gfa03 { get; set; }
        public decimal gfa04 { get; set; }
        public string gfa05 { get; set; }
        public string gfa06 { get; set; }
        public string gfa07 { get; set; }
        public decimal gfa08 { get; set; }
        public decimal gfa09 { get; set; }
        public string gfa10 { get; set; }
        public string gfa11 { get; set; }
        public string gfa12 { get; set; }
        public string gfa13 { get; set; }
        public string gfa14 { get; set; }
        public string gfa15 { get; set; }
        public string gfa16 { get; set; }
        public string gfa17 { get; set; }
        public string gfa18 { get; set; }
        public string gfa19 { get; set; }
        public string gfa20 { get; set; }
        public decimal gfaprno { get; set; }
        public string gfaconf { get; set; }
        public Nullable<System.DateTime> gfacond { get; set; }
        public string gfaconu { get; set; }
        public string gfapost { get; set; }
        public Nullable<System.DateTime> gfaposd { get; set; }
        public string gfaposu { get; set; }
        public string gfacomp { get; set; }
        public string gfacreu { get; set; }
        public string gfacreg { get; set; }
        public Nullable<System.DateTime> gfacred { get; set; }
        public string gfamodu { get; set; }
        public string gfamodg { get; set; }
        public Nullable<System.DateTime> gfamodd { get; set; }
        public string gfasecu { get; set; }
        public string gfasecg { get; set; }
    }
}
