//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ica_tb_0606
    {
        public string ica01 { get; set; }
        public string ica02 { get; set; }
        public string ica03 { get; set; }
        public string ica04 { get; set; }
        public string ica05 { get; set; }
        public string ica06 { get; set; }
        public string ica07 { get; set; }
        public string ica08 { get; set; }
        public string ica09 { get; set; }
        public decimal ica10 { get; set; }
        public decimal ica11 { get; set; }
        public decimal ica12 { get; set; }
        public decimal ica13 { get; set; }
        public decimal ica14 { get; set; }
        public decimal ica15 { get; set; }
        public decimal ica16 { get; set; }
        public string ica17 { get; set; }
        public decimal ica18 { get; set; }
        public decimal ica19 { get; set; }
        public Nullable<System.DateTime> ica20 { get; set; }
        public string ica21 { get; set; }
        public string ica22 { get; set; }
        public string ica23 { get; set; }
        public Nullable<decimal> ica24 { get; set; }
        public Nullable<System.DateTime> ica25 { get; set; }
        public decimal ica26 { get; set; }
        public string ica27 { get; set; }
        public string ica28 { get; set; }
        public string ica29 { get; set; }
        public string ica30 { get; set; }
        public string ica31 { get; set; }
        public string ica32 { get; set; }
        public string ica33 { get; set; }
        public string ica34 { get; set; }
        public string ica35 { get; set; }
        public string ica36 { get; set; }
        public string ica37 { get; set; }
        public string ica38 { get; set; }
        public string ica39 { get; set; }
        public string ica40 { get; set; }
        public string ica41 { get; set; }
        public string ica42 { get; set; }
        public string ica43 { get; set; }
        public string ica44 { get; set; }
        public string ica45 { get; set; }
        public string ica46 { get; set; }
        public string ica47 { get; set; }
        public string ica48 { get; set; }
        public string ica49 { get; set; }
        public string ica50 { get; set; }
        public string ica51 { get; set; }
        public string ica52 { get; set; }
        public string ica53 { get; set; }
        public string ica54 { get; set; }
        public string ica55 { get; set; }
        public string ica56 { get; set; }
        public string ica57 { get; set; }
        public string ica58 { get; set; }
        public string ica59 { get; set; }
        public string ica60 { get; set; }
        public string ica61 { get; set; }
        public string ica62 { get; set; }
        public string ica63 { get; set; }
        public string ica64 { get; set; }
        public string ica65 { get; set; }
        public string ica66 { get; set; }
        public string ica67 { get; set; }
        public string ica68 { get; set; }
        public string ica69 { get; set; }
        public string ica70 { get; set; }
        public string ica71 { get; set; }
        public string ica72 { get; set; }
        public string ica73 { get; set; }
        public string ica74 { get; set; }
        public string ica75 { get; set; }
        public string ica76 { get; set; }
        public string ica77 { get; set; }
        public string ica78 { get; set; }
        public string ica79 { get; set; }
        public string ica80 { get; set; }
        public string icaconf { get; set; }
        public string icavali { get; set; }
        public string icacreu { get; set; }
        public string icacreg { get; set; }
        public Nullable<System.DateTime> icacred { get; set; }
        public string icamodu { get; set; }
        public string icamodg { get; set; }
        public Nullable<System.DateTime> icamodd { get; set; }
        public string icasecu { get; set; }
        public string icasecg { get; set; }
    }
}
