//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ila_tb
    {
        public string ila01 { get; set; }
        public Nullable<System.DateTime> ila02 { get; set; }
        public string ila03 { get; set; }
        public string ila04 { get; set; }
        public string ila05 { get; set; }
        public string ila06 { get; set; }
        public decimal ila07 { get; set; }
        public string ila08 { get; set; }
        public string ila09 { get; set; }
        public string ila10 { get; set; }
        public string ila11 { get; set; }
        public string ila12 { get; set; }
        public decimal ila13 { get; set; }
        public decimal ila13t { get; set; }
        public decimal ila13g { get; set; }
        public string ila14 { get; set; }
        public string ila15 { get; set; }
        public string ila16 { get; set; }
        public string ila17 { get; set; }
        public string ila18 { get; set; }
        public string ila19 { get; set; }
        public decimal ila20 { get; set; }
        public string ila21 { get; set; }
        public string ila22 { get; set; }
        public string ila23 { get; set; }
        public string ila24 { get; set; }
        public string ila25 { get; set; }
        public string ilaconf { get; set; }
        public Nullable<System.DateTime> ilacond { get; set; }
        public string ilaconu { get; set; }
        public string ilastat { get; set; }
        public string ilacomp { get; set; }
        public string ilacreu { get; set; }
        public string ilacreg { get; set; }
        public Nullable<System.DateTime> ilacred { get; set; }
        public string ilamodu { get; set; }
        public string ilamodg { get; set; }
        public Nullable<System.DateTime> ilamodd { get; set; }
        public string ilasecu { get; set; }
        public string ilasecg { get; set; }
    }
}
