//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class imb_tb
    {
        public string imb01 { get; set; }
        public decimal imb02 { get; set; }
        public string imb03 { get; set; }
        public string imb04 { get; set; }
        public decimal imb05 { get; set; }
        public string imb06 { get; set; }
        public string imb07 { get; set; }
        public decimal imb08 { get; set; }
        public decimal imb09 { get; set; }
        public decimal imb10 { get; set; }
        public decimal imb10t { get; set; }
        public string imb11 { get; set; }
        public Nullable<decimal> imb12 { get; set; }
        public decimal imb13 { get; set; }
        public decimal imb14 { get; set; }
        public string imb15 { get; set; }
        public decimal imb16 { get; set; }
        public string imb17 { get; set; }
        public string imb18 { get; set; }
        public string imb19 { get; set; }
        public string imb20 { get; set; }
        public string imb21 { get; set; }
        public string imb22 { get; set; }
        public string imb23 { get; set; }
        public string imb24 { get; set; }
        public string imb25 { get; set; }
        public string imbcomp { get; set; }
        public string imbcreu { get; set; }
        public string imbcreg { get; set; }
        public Nullable<System.DateTime> imbcred { get; set; }
        public string imbmodu { get; set; }
        public string imbmodg { get; set; }
        public Nullable<System.DateTime> imbmodd { get; set; }
    }
}
