//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class jja_tb
    {
        public string jja01 { get; set; }
        public string jja02 { get; set; }
        public decimal jja03 { get; set; }
        public string jja04 { get; set; }
        public string jja05 { get; set; }
        public Nullable<System.DateTime> jja06 { get; set; }
        public string jja07 { get; set; }
        public string jja07_c { get; set; }
        public decimal jja08 { get; set; }
        public decimal jja09 { get; set; }
        public decimal jja10 { get; set; }
        public string jja11 { get; set; }
        public string jja12 { get; set; }
        public string jja13 { get; set; }
        public string jja14 { get; set; }
        public Nullable<decimal> jja15 { get; set; }
        public Nullable<System.DateTime> jja16 { get; set; }
        public string jja17 { get; set; }
        public string jja17_c { get; set; }
        public decimal jja18 { get; set; }
        public decimal jja19 { get; set; }
        public decimal jja20 { get; set; }
        public string jja21 { get; set; }
        public string jja22 { get; set; }
        public string jja23 { get; set; }
        public decimal jja24 { get; set; }
        public string jja25 { get; set; }
        public string jja26 { get; set; }
        public string jja27 { get; set; }
        public string jja28 { get; set; }
        public string jja29 { get; set; }
        public string jja30 { get; set; }
        public string jja31 { get; set; }
        public string jja32 { get; set; }
        public string jja33 { get; set; }
        public string jja34 { get; set; }
        public string jja35 { get; set; }
        public string jja36 { get; set; }
        public string jja37 { get; set; }
        public string jja38 { get; set; }
        public string jja39 { get; set; }
        public string jja40 { get; set; }
        public string jja41 { get; set; }
        public string jja42 { get; set; }
        public string jjacreu { get; set; }
        public string jjacreg { get; set; }
        public Nullable<System.DateTime> jjacred { get; set; }
        public string jjamodu { get; set; }
        public string jjamodg { get; set; }
        public Nullable<System.DateTime> jjamodd { get; set; }
        public string jjasecu { get; set; }
        public string jjasecg { get; set; }
    }
}
