//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mea_tb
    {
        public string mea00 { get; set; }
        public string mea01 { get; set; }
        public Nullable<System.DateTime> mea02 { get; set; }
        public string mea03 { get; set; }
        public string mea04 { get; set; }
        public string mea05 { get; set; }
        public string mea06 { get; set; }
        public decimal mea07 { get; set; }
        public string mea08 { get; set; }
        public string mea09 { get; set; }
        public string mea10 { get; set; }
        public string mea11 { get; set; }
        public string mea12 { get; set; }
        public decimal mea13 { get; set; }
        public decimal mea14 { get; set; }
        public decimal mea14t { get; set; }
        public Nullable<System.DateTime> mea15 { get; set; }
        public Nullable<System.DateTime> mea16 { get; set; }
        public Nullable<System.DateTime> mea17 { get; set; }
        public Nullable<System.DateTime> mea18 { get; set; }
        public string mea19 { get; set; }
        public string mea20 { get; set; }
        public string mea21 { get; set; }
        public decimal mea22 { get; set; }
        public string mea23 { get; set; }
        public string mea24 { get; set; }
        public Nullable<decimal> mea25 { get; set; }
        public decimal mea26 { get; set; }
        public decimal mea27 { get; set; }
        public string mea28 { get; set; }
        public string mea29 { get; set; }
        public string mea30 { get; set; }
        public string mea31 { get; set; }
        public string mea32 { get; set; }
        public string mea33 { get; set; }
        public string mea34 { get; set; }
        public string mea35 { get; set; }
        public string mea36 { get; set; }
        public string mea37 { get; set; }
        public string mea38 { get; set; }
        public string mea39 { get; set; }
        public string mea40 { get; set; }
        public string meastat { get; set; }
        public string meaconf { get; set; }
        public string meaconu { get; set; }
        public Nullable<System.DateTime> meacond { get; set; }
        public string meacomp { get; set; }
        public string meacreu { get; set; }
        public string meacreg { get; set; }
        public Nullable<System.DateTime> meacred { get; set; }
        public string meamodu { get; set; }
        public string meamodg { get; set; }
        public Nullable<System.DateTime> meamodd { get; set; }
        public string measecu { get; set; }
        public string measecg { get; set; }
    }
}
