//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mfb_tb
    {
        public string mfb01 { get; set; }
        public decimal mfb02 { get; set; }
        public string mfb03 { get; set; }
        public string mfb04 { get; set; }
        public decimal mfb05 { get; set; }
        public string mfb06 { get; set; }
        public string mfb07 { get; set; }
        public string mfb08 { get; set; }
        public string mfb09 { get; set; }
        public string mfb10 { get; set; }
        public Nullable<decimal> mfb11 { get; set; }
        public string mfb12 { get; set; }
        public string mfb13 { get; set; }
        public string mfb14 { get; set; }
        public string mfb15 { get; set; }
        public string mfb16 { get; set; }
        public string mfb17 { get; set; }
        public string mfb18 { get; set; }
        public string mfbcomp { get; set; }
        public string mfbcreu { get; set; }
        public string mfbcreg { get; set; }
        public Nullable<System.DateTime> mfbcred { get; set; }
        public string mfbmodu { get; set; }
        public string mfbmodg { get; set; }
        public Nullable<System.DateTime> mfbmodd { get; set; }
    }
}
