//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mga_tb
    {
        public string mga00 { get; set; }
        public string mga01 { get; set; }
        public Nullable<System.DateTime> mga02 { get; set; }
        public string mga03 { get; set; }
        public string mga04 { get; set; }
        public string mga05 { get; set; }
        public string mga06 { get; set; }
        public string mga07 { get; set; }
        public string mga08 { get; set; }
        public string mga09 { get; set; }
        public string mga10 { get; set; }
        public string mga11 { get; set; }
        public string mga12 { get; set; }
        public string mga13 { get; set; }
        public string mga14 { get; set; }
        public string mga15 { get; set; }
        public string mgaconf { get; set; }
        public string mgaconu { get; set; }
        public Nullable<System.DateTime> mgacond { get; set; }
        public string mgacomp { get; set; }
        public string mgacreu { get; set; }
        public string mgacreg { get; set; }
        public Nullable<System.DateTime> mgacred { get; set; }
        public string mgamodu { get; set; }
        public string mgamodg { get; set; }
        public Nullable<System.DateTime> mgamodd { get; set; }
        public string mgasecu { get; set; }
        public string mgasecg { get; set; }
    }
}
