//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgb_tb
    {
        public string mgb01 { get; set; }
        public decimal mgb02 { get; set; }
        public string mgb03 { get; set; }
        public string mgb04 { get; set; }
        public decimal mgb05 { get; set; }
        public string mgb06 { get; set; }
        public string mgb07 { get; set; }
        public string mgb08 { get; set; }
        public string mgb09 { get; set; }
        public string mgb10 { get; set; }
        public Nullable<decimal> mgb11 { get; set; }
        public string mgb12 { get; set; }
        public string mgb13 { get; set; }
        public string mgb14 { get; set; }
        public string mgb15 { get; set; }
        public string mgb16 { get; set; }
        public string mgb17 { get; set; }
        public string mgb18 { get; set; }
        public string mgbcomp { get; set; }
        public string mgbcreu { get; set; }
        public string mgbcreg { get; set; }
        public Nullable<System.DateTime> mgbcred { get; set; }
        public string mgbmodu { get; set; }
        public string mgbmodg { get; set; }
        public Nullable<System.DateTime> mgbmodd { get; set; }
    }
}
