//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mhb_tb
    {
        public string mhb01 { get; set; }
        public decimal mhb02 { get; set; }
        public string mhb03 { get; set; }
        public string mhb04 { get; set; }
        public decimal mhb05 { get; set; }
        public string mhb06 { get; set; }
        public string mhb07 { get; set; }
        public string mhb08 { get; set; }
        public decimal mhb09 { get; set; }
        public decimal mhb10 { get; set; }
        public decimal mhb10t { get; set; }
        public string mhb11 { get; set; }
        public string mhb12 { get; set; }
        public string mhb13 { get; set; }
        public string mhb14 { get; set; }
        public string mhb15 { get; set; }
        public string mhb16 { get; set; }
        public string mhb17 { get; set; }
        public string mhb18 { get; set; }
        public string mhb19 { get; set; }
        public string mhb20 { get; set; }
        public string mhbcomp { get; set; }
        public string mhbcreu { get; set; }
        public string mhbcreg { get; set; }
        public Nullable<System.DateTime> mhbcred { get; set; }
        public string mhbmodu { get; set; }
        public string mhbmodg { get; set; }
        public Nullable<System.DateTime> mhbmodd { get; set; }
    }
}
