//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mia_tb
    {
        public string mia00 { get; set; }
        public string mia01 { get; set; }
        public Nullable<System.DateTime> mia02 { get; set; }
        public string mia03 { get; set; }
        public string mia04 { get; set; }
        public string mia05 { get; set; }
        public string mia06 { get; set; }
        public decimal mia07 { get; set; }
        public string mia08 { get; set; }
        public string mia09 { get; set; }
        public string mia10 { get; set; }
        public string mia11 { get; set; }
        public string mia12 { get; set; }
        public decimal mia13 { get; set; }
        public decimal mia13t { get; set; }
        public decimal mia13g { get; set; }
        public string mia14 { get; set; }
        public string mia15 { get; set; }
        public string mia16 { get; set; }
        public string mia17 { get; set; }
        public string mia18 { get; set; }
        public string mia19 { get; set; }
        public string mia20 { get; set; }
        public string miaconf { get; set; }
        public string miaconu { get; set; }
        public Nullable<System.DateTime> miacond { get; set; }
        public string miacomp { get; set; }
        public string miacreu { get; set; }
        public string miacreg { get; set; }
        public Nullable<System.DateTime> miacred { get; set; }
        public string miamodu { get; set; }
        public string miamodg { get; set; }
        public Nullable<System.DateTime> miamodd { get; set; }
        public string miasecu { get; set; }
        public string miasecg { get; set; }
    }
}
