//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbb_tb
    {
        public string pbb01 { get; set; }
        public string pbb02 { get; set; }
        public string pbb03 { get; set; }
        public string pbb04 { get; set; }
        public string pbb05 { get; set; }
        public string pbbcreu { get; set; }
        public string pbbcreg { get; set; }
        public Nullable<System.DateTime> pbbcred { get; set; }
        public string pbbmodu { get; set; }
        public string pbbmodg { get; set; }
        public Nullable<System.DateTime> pbbmodd { get; set; }
        public string pbbsecu { get; set; }
        public string pbbsecg { get; set; }
    }
}
