//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbc_tb
    {
        public string pbc01 { get; set; }
        public decimal pbc02 { get; set; }
        public string pbc03 { get; set; }
        public decimal pbc04 { get; set; }
        public string pbc05 { get; set; }
        public string pbc06 { get; set; }
        public string pbc07 { get; set; }
        public string pbccreu { get; set; }
        public string pbccreg { get; set; }
        public Nullable<System.DateTime> pbccred { get; set; }
        public string pbcmodu { get; set; }
        public string pbcmodg { get; set; }
        public Nullable<System.DateTime> pbcmodd { get; set; }
    }
}
