//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pca_tb
    {
        public string pca01 { get; set; }
        public string pca02 { get; set; }
        public string pca03 { get; set; }
        public string pca04 { get; set; }
        public string pca05 { get; set; }
        public string pca06 { get; set; }
        public string pca07 { get; set; }
        public string pca08 { get; set; }
        public string pca09 { get; set; }
        public string pca10 { get; set; }
        public string pca11 { get; set; }
        public string pca12 { get; set; }
        public Nullable<decimal> pca13 { get; set; }
        public Nullable<decimal> pca14 { get; set; }
        public Nullable<decimal> pca15 { get; set; }
        public string pca16 { get; set; }
        public string pca17 { get; set; }
        public string pca18 { get; set; }
        public string pca19 { get; set; }
        public string pca20 { get; set; }
        public string pca21 { get; set; }
        public string pca22 { get; set; }
        public string pca23 { get; set; }
        public string pca24 { get; set; }
        public string pca25 { get; set; }
        public string pca26 { get; set; }
        public string pca27 { get; set; }
        public string pca28 { get; set; }
        public Nullable<decimal> pca29 { get; set; }
        public Nullable<System.DateTime> pca30 { get; set; }
        public Nullable<System.DateTime> pca31 { get; set; }
        public string pca32 { get; set; }
        public string pca33 { get; set; }
        public string pca34 { get; set; }
        public string pca35 { get; set; }
        public string pca36 { get; set; }
        public string pca37 { get; set; }
        public string pca38 { get; set; }
        public string pca39 { get; set; }
        public string pca40 { get; set; }
        public string pca41 { get; set; }
        public string pca42 { get; set; }
        public string pca43 { get; set; }
        public string pca44 { get; set; }
        public string pca45 { get; set; }
        public string pcaconf { get; set; }
        public string pcavali { get; set; }
        public string pcacreu { get; set; }
        public string pcacreg { get; set; }
        public Nullable<System.DateTime> pcacred { get; set; }
        public string pcamodu { get; set; }
        public string pcamodg { get; set; }
        public Nullable<System.DateTime> pcamodd { get; set; }
        public string pcasecu { get; set; }
        public string pcasecg { get; set; }
    }
}
