//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcc_tb
    {
        public string pcc01 { get; set; }
        public string pcc02 { get; set; }
        public string pcc03 { get; set; }
        public string pcc04 { get; set; }
        public string pcc05 { get; set; }
        public string pcc06 { get; set; }
        public string pcc07 { get; set; }
        public string pcc08 { get; set; }
        public string pcc09 { get; set; }
        public string pccvali { get; set; }
        public string pcccreu { get; set; }
        public string pcccreg { get; set; }
        public Nullable<System.DateTime> pcccred { get; set; }
        public string pccmodu { get; set; }
        public string pccmodg { get; set; }
        public Nullable<System.DateTime> pccmodd { get; set; }
        public string pccsecu { get; set; }
        public string pccsecg { get; set; }
    }
}
