//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pea_tb
    {
        public string pea01 { get; set; }
        public Nullable<System.DateTime> pea02 { get; set; }
        public string pea03 { get; set; }
        public string pea04 { get; set; }
        public string pea05 { get; set; }
        public string pea06 { get; set; }
        public decimal pea07 { get; set; }
        public string pea08 { get; set; }
        public string pea09 { get; set; }
        public string pea10 { get; set; }
        public string pea11 { get; set; }
        public string pea12 { get; set; }
        public string pea13 { get; set; }
        public decimal pea14 { get; set; }
        public string pea15 { get; set; }
        public string pea16 { get; set; }
        public string pea17 { get; set; }
        public string peaconf { get; set; }
        public Nullable<System.DateTime> peacond { get; set; }
        public string peaconu { get; set; }
        public string peastat { get; set; }
        public string peacomp { get; set; }
        public string peacreu { get; set; }
        public string peacreg { get; set; }
        public Nullable<System.DateTime> peacred { get; set; }
        public string peamodu { get; set; }
        public string peamodg { get; set; }
        public Nullable<System.DateTime> peamodd { get; set; }
        public string peasecu { get; set; }
        public string peasecg { get; set; }
    }
}
