//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfa_tb
    {
        public string pfa01 { get; set; }
        public Nullable<System.DateTime> pfa02 { get; set; }
        public string pfa03 { get; set; }
        public string pfa04 { get; set; }
        public string pfa05 { get; set; }
        public string pfa06 { get; set; }
        public decimal pfa07 { get; set; }
        public string pfa08 { get; set; }
        public string pfa09 { get; set; }
        public string pfa10 { get; set; }
        public string pfa11 { get; set; }
        public string pfa12 { get; set; }
        public decimal pfa13 { get; set; }
        public decimal pfa13t { get; set; }
        public decimal pfa13g { get; set; }
        public string pfa14 { get; set; }
        public string pfa15 { get; set; }
        public string pfa16 { get; set; }
        public decimal pfa17 { get; set; }
        public string pfa18 { get; set; }
        public string pfa19 { get; set; }
        public Nullable<decimal> pfa20 { get; set; }
        public string pfa21 { get; set; }
        public string pfa22 { get; set; }
        public string pfa23 { get; set; }
        public string pfa24 { get; set; }
        public string pfa25 { get; set; }
        public string pfa26 { get; set; }
        public string pfa27 { get; set; }
        public string pfa28 { get; set; }
        public string pfa29 { get; set; }
        public string pfa30 { get; set; }
        public string pfa31 { get; set; }
        public string pfa32 { get; set; }
        public string pfa33 { get; set; }
        public string pfa34 { get; set; }
        public string pfa35 { get; set; }
        public string pfa36 { get; set; }
        public string pfa37 { get; set; }
        public string pfa38 { get; set; }
        public string pfa39 { get; set; }
        public string pfa40 { get; set; }
        public string pfa41 { get; set; }
        public string pfa42 { get; set; }
        public string pfa43 { get; set; }
        public string pfa44 { get; set; }
        public string pfa45 { get; set; }
        public string pfaconf { get; set; }
        public Nullable<System.DateTime> pfacond { get; set; }
        public string pfaconu { get; set; }
        public string pfastat { get; set; }
        public string pfacomp { get; set; }
        public string pfacreu { get; set; }
        public string pfacreg { get; set; }
        public Nullable<System.DateTime> pfacred { get; set; }
        public string pfamodu { get; set; }
        public string pfamodg { get; set; }
        public Nullable<System.DateTime> pfamodd { get; set; }
        public string pfasecu { get; set; }
        public string pfasecg { get; set; }
    }
}
