//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfb_tb
    {
        public string pfb01 { get; set; }
        public decimal pfb02 { get; set; }
        public string pfb03 { get; set; }
        public string pfb04 { get; set; }
        public decimal pfb05 { get; set; }
        public string pfb06 { get; set; }
        public string pfb07 { get; set; }
        public decimal pfb08 { get; set; }
        public decimal pfb09 { get; set; }
        public decimal pfb10 { get; set; }
        public decimal pfb10t { get; set; }
        public string pfb11 { get; set; }
        public Nullable<decimal> pfb12 { get; set; }
        public decimal pfb13 { get; set; }
        public decimal pfb14 { get; set; }
        public string pfb15 { get; set; }
        public string pfb16 { get; set; }
        public decimal pfb17 { get; set; }
        public Nullable<System.DateTime> pfb18 { get; set; }
        public Nullable<System.DateTime> pfb19 { get; set; }
        public string pfb20 { get; set; }
        public string pfb21 { get; set; }
        public string pfb22 { get; set; }
        public string pfb23 { get; set; }
        public string pfb24 { get; set; }
        public string pfb25 { get; set; }
        public string pfb26 { get; set; }
        public string pfb27 { get; set; }
        public string pfb28 { get; set; }
        public string pfb29 { get; set; }
        public string pfb30 { get; set; }
        public string pfb31 { get; set; }
        public string pfb32 { get; set; }
        public string pfb33 { get; set; }
        public string pfb34 { get; set; }
        public string pfb35 { get; set; }
        public string pfbcomp { get; set; }
        public string pfbcreu { get; set; }
        public string pfbcreg { get; set; }
        public Nullable<System.DateTime> pfbcred { get; set; }
        public string pfbmodu { get; set; }
        public string pfbmodg { get; set; }
        public Nullable<System.DateTime> pfbmodd { get; set; }
    }
}
