//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pga_tb
    {
        public string pga01 { get; set; }
        public Nullable<System.DateTime> pga02 { get; set; }
        public string pga03 { get; set; }
        public string pga04 { get; set; }
        public string pga05 { get; set; }
        public string pga06 { get; set; }
        public decimal pga07 { get; set; }
        public string pga08 { get; set; }
        public string pga09 { get; set; }
        public string pga10 { get; set; }
        public string pga11 { get; set; }
        public string pga12 { get; set; }
        public decimal pga13 { get; set; }
        public decimal pga13t { get; set; }
        public decimal pga13g { get; set; }
        public string pga14 { get; set; }
        public string pga15 { get; set; }
        public string pga16 { get; set; }
        public string pga17 { get; set; }
        public decimal pga18 { get; set; }
        public string pga19 { get; set; }
        public string pga20 { get; set; }
        public string pga21 { get; set; }
        public string pga22 { get; set; }
        public string pga23 { get; set; }
        public string pga24 { get; set; }
        public string pga25 { get; set; }
        public string pga26 { get; set; }
        public string pga27 { get; set; }
        public string pga28 { get; set; }
        public string pga29 { get; set; }
        public string pga30 { get; set; }
        public string pga31 { get; set; }
        public string pga32 { get; set; }
        public string pga33 { get; set; }
        public string pga34 { get; set; }
        public string pga35 { get; set; }
        public string pga36 { get; set; }
        public string pga37 { get; set; }
        public string pga38 { get; set; }
        public string pga39 { get; set; }
        public string pga40 { get; set; }
        public string pga41 { get; set; }
        public string pga42 { get; set; }
        public string pga43 { get; set; }
        public string pga44 { get; set; }
        public string pga45 { get; set; }
        public string pgaconf { get; set; }
        public Nullable<System.DateTime> pgacond { get; set; }
        public string pgaconu { get; set; }
        public string pgastat { get; set; }
        public string pgacomp { get; set; }
        public string pgacreu { get; set; }
        public string pgacreg { get; set; }
        public Nullable<System.DateTime> pgacred { get; set; }
        public string pgamodu { get; set; }
        public string pgamodg { get; set; }
        public Nullable<System.DateTime> pgamodd { get; set; }
        public string pgasecu { get; set; }
        public string pgasecg { get; set; }
    }
}
