//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pgb_tb
    {
        public string pgb01 { get; set; }
        public decimal pgb02 { get; set; }
        public string pgb03 { get; set; }
        public string pgb04 { get; set; }
        public decimal pgb05 { get; set; }
        public string pgb06 { get; set; }
        public string pgb07 { get; set; }
        public decimal pgb08 { get; set; }
        public decimal pgb09 { get; set; }
        public decimal pgb10 { get; set; }
        public decimal pgb10t { get; set; }
        public string pgb11 { get; set; }
        public Nullable<decimal> pgb12 { get; set; }
        public decimal pgb13 { get; set; }
        public decimal pgb14 { get; set; }
        public string pgb15 { get; set; }
        public string pgb16 { get; set; }
        public decimal pgb17 { get; set; }
        public decimal pgb18 { get; set; }
        public string pgb19 { get; set; }
        public string pgb20 { get; set; }
        public string pgb21 { get; set; }
        public string pgb22 { get; set; }
        public string pgb23 { get; set; }
        public string pgb24 { get; set; }
        public string pgb25 { get; set; }
        public string pgb26 { get; set; }
        public string pgb27 { get; set; }
        public string pgb28 { get; set; }
        public string pgb29 { get; set; }
        public string pgb30 { get; set; }
        public string pgb31 { get; set; }
        public string pgb32 { get; set; }
        public string pgb33 { get; set; }
        public string pgb34 { get; set; }
        public string pgb35 { get; set; }
        public string pgbcomp { get; set; }
        public string pgbcreu { get; set; }
        public string pgbcreg { get; set; }
        public Nullable<System.DateTime> pgbcred { get; set; }
        public string pgbmodu { get; set; }
        public string pgbmodg { get; set; }
        public Nullable<System.DateTime> pgbmodd { get; set; }
    }
}
