//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class phb_tb
    {
        public string phb01 { get; set; }
        public decimal phb02 { get; set; }
        public string phb03 { get; set; }
        public string phb04 { get; set; }
        public decimal phb05 { get; set; }
        public string phb06 { get; set; }
        public string phb07 { get; set; }
        public decimal phb08 { get; set; }
        public decimal phb09 { get; set; }
        public decimal phb10 { get; set; }
        public decimal phb10t { get; set; }
        public string phb11 { get; set; }
        public Nullable<decimal> phb12 { get; set; }
        public decimal phb13 { get; set; }
        public decimal phb14 { get; set; }
        public string phb15 { get; set; }
        public string phb16 { get; set; }
        public string phb17 { get; set; }
        public decimal phb18 { get; set; }
        public string phb19 { get; set; }
        public string phb20 { get; set; }
        public string phb21 { get; set; }
        public string phb22 { get; set; }
        public string phb23 { get; set; }
        public string phb24 { get; set; }
        public string phb25 { get; set; }
        public string phbcomp { get; set; }
        public string phbcreu { get; set; }
        public string phbcreg { get; set; }
        public Nullable<System.DateTime> phbcred { get; set; }
        public string phbmodu { get; set; }
        public string phbmodg { get; set; }
        public Nullable<System.DateTime> phbmodd { get; set; }
    }
}
