//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class saV_tb_desc
    {
        public string Table_Name { get; set; }
        public string Field_name { get; set; }
        public string xtype { get; set; }
        public string cell_length { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> smallid { get; set; }
        public string type { get; set; }
        public string name { get; set; }
    }
}
