//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sba_tb
    {
        public string sba01 { get; set; }
        public string sba02 { get; set; }
        public string sba03 { get; set; }
        public string sba04 { get; set; }
        public string sba05 { get; set; }
        public string sbavali { get; set; }
        public string sbacreu { get; set; }
        public string sbacreg { get; set; }
        public Nullable<System.DateTime> sbacred { get; set; }
        public string sbamodu { get; set; }
        public string sbamodg { get; set; }
        public Nullable<System.DateTime> sbamodd { get; set; }
        public string sbasecu { get; set; }
        public string sbasecg { get; set; }
    }
}
