//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbb_tb
    {
        public string sbb01 { get; set; }
        public string sbb02 { get; set; }
        public string sbb03 { get; set; }
        public string sbb04 { get; set; }
        public string sbb05 { get; set; }
        public string sbbcreu { get; set; }
        public string sbbcreg { get; set; }
        public Nullable<System.DateTime> sbbcred { get; set; }
        public string sbbmodu { get; set; }
        public string sbbmodg { get; set; }
        public Nullable<System.DateTime> sbbmodd { get; set; }
        public string sbbsecu { get; set; }
        public string sbbsecg { get; set; }
    }
}
