//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbg_tb
    {
        public string sbg01 { get; set; }
        public string sbg02 { get; set; }
        public string sbg03 { get; set; }
        public string sbg04 { get; set; }
        public string sbg05 { get; set; }
        public string sbgcreu { get; set; }
        public string sbgcreg { get; set; }
        public Nullable<System.DateTime> sbgcred { get; set; }
        public string sbgmodu { get; set; }
        public string sbgmodg { get; set; }
        public Nullable<System.DateTime> sbgmodd { get; set; }
        public string sbgsecu { get; set; }
        public string sbgsecg { get; set; }
    }
}
