//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sfa_tb
    {
        public string sfa01 { get; set; }
        public Nullable<System.DateTime> sfa02 { get; set; }
        public string sfa03 { get; set; }
        public string sfa04 { get; set; }
        public string sfa05 { get; set; }
        public string sfa06 { get; set; }
        public decimal sfa07 { get; set; }
        public string sfa08 { get; set; }
        public string sfa09 { get; set; }
        public string sfa10 { get; set; }
        public string sfa11 { get; set; }
        public string sfa12 { get; set; }
        public decimal sfa13 { get; set; }
        public decimal sfa13t { get; set; }
        public decimal sfa13g { get; set; }
        public string sfa14 { get; set; }
        public string sfa15 { get; set; }
        public string sfa16 { get; set; }
        public string sfa17 { get; set; }
        public string sfa18 { get; set; }
        public string sfa19 { get; set; }
        public string sfa20 { get; set; }
        public decimal sfa21 { get; set; }
        public string sfa22 { get; set; }
        public string sfa23 { get; set; }
        public string sfa24 { get; set; }
        public string sfa25 { get; set; }
        public string sfa26 { get; set; }
        public string sfa27 { get; set; }
        public string sfa28 { get; set; }
        public string sfa29 { get; set; }
        public string sfa30 { get; set; }
        public string sfa31 { get; set; }
        public string sfa32 { get; set; }
        public string sfa33 { get; set; }
        public string sfa34 { get; set; }
        public string sfa35 { get; set; }
        public string sfa36 { get; set; }
        public string sfa37 { get; set; }
        public string sfa38 { get; set; }
        public string sfa39 { get; set; }
        public string sfa40 { get; set; }
        public string sfa41 { get; set; }
        public string sfa42 { get; set; }
        public string sfa43 { get; set; }
        public string sfa44 { get; set; }
        public string sfa45 { get; set; }
        public string sfa46 { get; set; }
        public string sfa47 { get; set; }
        public string sfa48 { get; set; }
        public string sfa49 { get; set; }
        public string sfa50 { get; set; }
        public string sfaconf { get; set; }
        public Nullable<System.DateTime> sfacond { get; set; }
        public string sfaconu { get; set; }
        public string sfastat { get; set; }
        public string sfacomp { get; set; }
        public string sfacreu { get; set; }
        public string sfacreg { get; set; }
        public Nullable<System.DateTime> sfacred { get; set; }
        public string sfamodu { get; set; }
        public string sfamodg { get; set; }
        public Nullable<System.DateTime> sfamodd { get; set; }
        public string sfasecu { get; set; }
        public string sfasecg { get; set; }
    }
}
