//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sfb_tb
    {
        public string sfb01 { get; set; }
        public decimal sfb02 { get; set; }
        public string sfb03 { get; set; }
        public string sfb04 { get; set; }
        public decimal sfb05 { get; set; }
        public string sfb06 { get; set; }
        public string sfb07 { get; set; }
        public decimal sfb08 { get; set; }
        public decimal sfb09 { get; set; }
        public decimal sfb10 { get; set; }
        public decimal sfb10t { get; set; }
        public string sfb11 { get; set; }
        public Nullable<decimal> sfb12 { get; set; }
        public decimal sfb13 { get; set; }
        public decimal sfb14 { get; set; }
        public string sfb15 { get; set; }
        public string sfb16 { get; set; }
        public decimal sfb17 { get; set; }
        public Nullable<System.DateTime> sfb18 { get; set; }
        public string sfb19 { get; set; }
        public string sfb20 { get; set; }
        public string sfb21 { get; set; }
        public string sfb22 { get; set; }
        public string sfb23 { get; set; }
        public string sfb24 { get; set; }
        public string sfb25 { get; set; }
        public string sfb26 { get; set; }
        public string sfb27 { get; set; }
        public string sfb28 { get; set; }
        public string sfb29 { get; set; }
        public string sfb30 { get; set; }
        public string sfb31 { get; set; }
        public string sfb32 { get; set; }
        public string sfb33 { get; set; }
        public string sfb34 { get; set; }
        public string sfb35 { get; set; }
        public string sfb36 { get; set; }
        public string sfb37 { get; set; }
        public string sfb38 { get; set; }
        public string sfb39 { get; set; }
        public string sfb40 { get; set; }
        public string sfbcomp { get; set; }
        public string sfbcreu { get; set; }
        public string sfbcreg { get; set; }
        public Nullable<System.DateTime> sfbcred { get; set; }
        public string sfbmodu { get; set; }
        public string sfbmodg { get; set; }
        public Nullable<System.DateTime> sfbmodd { get; set; }
    }
}
