//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sha_tb
    {
        public string sha01 { get; set; }
        public Nullable<System.DateTime> sha02 { get; set; }
        public string sha03 { get; set; }
        public string sha04 { get; set; }
        public string sha05 { get; set; }
        public string sha06 { get; set; }
        public decimal sha07 { get; set; }
        public string sha08 { get; set; }
        public string sha09 { get; set; }
        public string sha10 { get; set; }
        public string sha11 { get; set; }
        public string sha12 { get; set; }
        public decimal sha13 { get; set; }
        public decimal sha13t { get; set; }
        public decimal sha13g { get; set; }
        public decimal sha14 { get; set; }
        public string sha15 { get; set; }
        public string sha16 { get; set; }
        public string sha17 { get; set; }
        public string sha18 { get; set; }
        public string sha19 { get; set; }
        public string sha20 { get; set; }
        public string sha21 { get; set; }
        public string sha22 { get; set; }
        public string shaconf { get; set; }
        public Nullable<System.DateTime> shacond { get; set; }
        public string shaconu { get; set; }
        public string shastat { get; set; }
        public string shacomp { get; set; }
        public string shacreu { get; set; }
        public string shacreg { get; set; }
        public Nullable<System.DateTime> shacred { get; set; }
        public string shamodu { get; set; }
        public string shamodg { get; set; }
        public Nullable<System.DateTime> shamodd { get; set; }
        public string shasecu { get; set; }
        public string shasecg { get; set; }
    }
}
