//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tba_tb
    {
        public string tba01 { get; set; }
        public string tba02 { get; set; }
        public string tba03 { get; set; }
        public string tba04 { get; set; }
        public string tba05 { get; set; }
        public string tba06 { get; set; }
        public string tba07 { get; set; }
        public string tba08 { get; set; }
        public string tba09 { get; set; }
        public string tba10 { get; set; }
        public string tba11 { get; set; }
        public string tba12 { get; set; }
        public string tba13 { get; set; }
        public string tba14 { get; set; }
        public string tba15 { get; set; }
        public string tba16 { get; set; }
        public string tba17 { get; set; }
        public string tba18 { get; set; }
        public string tba19 { get; set; }
        public string tba20 { get; set; }
        public string tba21 { get; set; }
        public string tba22 { get; set; }
        public string tba23 { get; set; }
        public string tba24 { get; set; }
        public string tba25 { get; set; }
        public string tba26 { get; set; }
        public string tbavali { get; set; }
        public string tbacreu { get; set; }
        public string tbacreg { get; set; }
        public Nullable<System.DateTime> tbacred { get; set; }
        public string tbamodu { get; set; }
        public string tbamodg { get; set; }
        public Nullable<System.DateTime> tbamodd { get; set; }
    }
}
