//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tca_tb
    {
        public string tca01 { get; set; }
        public decimal tca02 { get; set; }
        public decimal tca03 { get; set; }
        public decimal tca04 { get; set; }
        public string tca05 { get; set; }
        public string tca06 { get; set; }
        public string tca07 { get; set; }
        public string tca08 { get; set; }
        public decimal tca09 { get; set; }
        public decimal tca09t { get; set; }
        public decimal tca09g { get; set; }
        public Nullable<System.DateTime> tca10 { get; set; }
        public string tca11 { get; set; }
        public string tca12 { get; set; }
        public string tca13 { get; set; }
        public string tca14 { get; set; }
        public string tca15 { get; set; }
        public string tca16 { get; set; }
        public string tca17 { get; set; }
        public string tca18 { get; set; }
        public string tca19 { get; set; }
        public string tca20 { get; set; }
        public string tca21 { get; set; }
        public string tca22 { get; set; }
        public string tca23 { get; set; }
        public string tca24 { get; set; }
        public string tca25 { get; set; }
        public string tca26 { get; set; }
        public string tcaconf { get; set; }
        public string tcaconu { get; set; }
        public Nullable<System.DateTime> tcacond { get; set; }
        public string tcacreu { get; set; }
        public string tcacreg { get; set; }
        public Nullable<System.DateTime> tcacred { get; set; }
        public string tcamodu { get; set; }
        public string tcamodg { get; set; }
        public Nullable<System.DateTime> tcamoddd { get; set; }
    }
}
