//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi120
    {
        public string ade01 { get; set; }
        public string ade02 { get; set; }
        public string ade03 { get; set; }
        public string ade04 { get; set; }
        public string ade05 { get; set; }
        public string ade06 { get; set; }
        public string adecreu { get; set; }
        public string adecreg { get; set; }
        public Nullable<System.DateTime> adecred { get; set; }
        public string ademodu { get; set; }
        public string ademodg { get; set; }
        public Nullable<System.DateTime> ademodd { get; set; }
        public string parents_ade01 { get; set; }
        public string parents_ade02 { get; set; }
    }
}
