//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi602s
    {
        public string adq01 { get; set; }
        public string adq02 { get; set; }
        public string adq03 { get; set; }
        public string adq04 { get; set; }
        public string adq05 { get; set; }
        public string adq06 { get; set; }
        public string adqcreu { get; set; }
        public string adqcreg { get; set; }
        public Nullable<System.DateTime> adqcred { get; set; }
        public string adqmodu { get; set; }
        public string adqmodg { get; set; }
        public Nullable<System.DateTime> adqmodd { get; set; }
    }
}
