//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi640
    {
        public string aze01 { get; set; }
        public string aze02 { get; set; }
        public string aze03 { get; set; }
        public string aze04 { get; set; }
        public string aze05 { get; set; }
        public string aze06 { get; set; }
        public string aze07 { get; set; }
        public string azecreu { get; set; }
        public string azecreg { get; set; }
        public Nullable<System.DateTime> azecred { get; set; }
        public string azemodu { get; set; }
        public string azemodg { get; set; }
        public Nullable<System.DateTime> azemodd { get; set; }
        public string azesecu { get; set; }
        public string azesecg { get; set; }
    }
}
