//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admq910
    {
        public short spid { get; set; }
        public string status { get; set; }
        public string login { get; set; }
        public string hostname { get; set; }
        public short blkBy { get; set; }
        public string dBName { get; set; }
        public string command { get; set; }
        public int cpuTime { get; set; }
        public long diskIO { get; set; }
        public System.DateTime lastBatch { get; set; }
        public string programName { get; set; }
        public string text { get; set; }
    }
}
