//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi620s
    {
        public string aza01 { get; set; }
        public string aza02 { get; set; }
        public string aza03 { get; set; }
        public string aza04 { get; set; }
        public string aza05 { get; set; }
        public Nullable<decimal> aza06 { get; set; }
        public Nullable<decimal> aza07 { get; set; }
        public string aza08 { get; set; }
        public Nullable<decimal> aza09 { get; set; }
        public Nullable<decimal> aza10 { get; set; }
        public Nullable<decimal> aza11 { get; set; }
        public string aza12 { get; set; }
        public string aza13 { get; set; }
        public string aza14 { get; set; }
        public string aza15 { get; set; }
        public string aza16 { get; set; }
        public string aza17 { get; set; }
        public string aza18 { get; set; }
        public string aza19 { get; set; }
        public string aza20 { get; set; }
        public string azacreu { get; set; }
        public string azacreg { get; set; }
        public Nullable<System.DateTime> azacred { get; set; }
        public string azamodu { get; set; }
        public string azamodg { get; set; }
        public Nullable<System.DateTime> azamodd { get; set; }
    }
}
