//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi650s
    {
        public string azq01 { get; set; }
        public decimal azq02 { get; set; }
        public string azq03 { get; set; }
        public string azq04 { get; set; }
        public string azq05 { get; set; }
        public string azq06 { get; set; }
        public string azq07 { get; set; }
        public Nullable<decimal> azq08 { get; set; }
        public string azq09 { get; set; }
        public string azq10 { get; set; }
        public string azq11 { get; set; }
        public string azqcreu { get; set; }
        public string azqcreg { get; set; }
        public Nullable<System.DateTime> azqcred { get; set; }
        public string azqmodu { get; set; }
        public string azqmodg { get; set; }
        public Nullable<System.DateTime> azqmodd { get; set; }
        public string azq03_c { get; set; }
        public string azq04_c { get; set; }
    }
}
