//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi110s
    {
        public string add01 { get; set; }
        public string add02 { get; set; }
        public string add03 { get; set; }
        public string add04 { get; set; }
        public string add05 { get; set; }
        public string add06 { get; set; }
        public string add07 { get; set; }
        public string add08 { get; set; }
        public string add09 { get; set; }
        public string add10 { get; set; }
        public string add11 { get; set; }
        public string add12 { get; set; }
        public string add13 { get; set; }
        public string add14 { get; set; }
        public string add15 { get; set; }
        public string add16 { get; set; }
        public string add17 { get; set; }
        public string add18 { get; set; }
        public string addcreu { get; set; }
        public string addcreg { get; set; }
        public Nullable<System.DateTime> addcred { get; set; }
        public string addmodu { get; set; }
        public string addmodg { get; set; }
        public Nullable<System.DateTime> addmodd { get; set; }
        public string add02_c { get; set; }
    }
}
