//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi611
    {
        public string adx01 { get; set; }
        public string adx02 { get; set; }
        public byte[] adx03 { get; set; }
        public string adx04 { get; set; }
        public string adx05 { get; set; }
        public string adxcreu { get; set; }
        public string adxcreg { get; set; }
        public Nullable<System.DateTime> adxcred { get; set; }
        public string adxmodu { get; set; }
        public string adxmodg { get; set; }
        public Nullable<System.DateTime> adxmodd { get; set; }
        public string adxsecu { get; set; }
        public string adxsecg { get; set; }
    }
}
