//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi100s
    {
        public string adb01 { get; set; }
        public string adb02 { get; set; }
        public string adb03 { get; set; }
        public string adb04 { get; set; }
        public string adb05 { get; set; }
        public string adbcreu { get; set; }
        public string adbcreg { get; set; }
        public Nullable<System.DateTime> adbcred { get; set; }
        public string adbmodu { get; set; }
        public string adbmodg { get; set; }
        public Nullable<System.DateTime> adbmodd { get; set; }
        public string adb02_c { get; set; }
    }
}
