//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi601s
    {
        public string adp01 { get; set; }
        public string adp02 { get; set; }
        public decimal adp03 { get; set; }
        public Nullable<decimal> adp04 { get; set; }
        public string adp05 { get; set; }
        public string adp06 { get; set; }
        public string adp07 { get; set; }
        public string adp08 { get; set; }
        public string adp09 { get; set; }
        public string adp10 { get; set; }
        public string adpcreu { get; set; }
        public string adpcreg { get; set; }
        public Nullable<System.DateTime> adpcred { get; set; }
        public string adpmodu { get; set; }
        public string adpmodg { get; set; }
        public Nullable<System.DateTime> adpmodd { get; set; }
        public string aza04 { get; set; }
        public string aza08 { get; set; }
        public Nullable<decimal> aza09 { get; set; }
        public Nullable<decimal> aza10 { get; set; }
        public Nullable<decimal> aza11 { get; set; }
    }
}
