//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admi610s
    {
        public string adm01 { get; set; }
        public string adm02 { get; set; }
        public Nullable<decimal> adm03 { get; set; }
        public string adm04 { get; set; }
        public string adm05 { get; set; }
        public string admcreu { get; set; }
        public string admcreg { get; set; }
        public Nullable<System.DateTime> admcred { get; set; }
        public string admmodu { get; set; }
        public string admmodg { get; set; }
        public Nullable<System.DateTime> admmodd { get; set; }
        public string adm02_c { get; set; }
    }
}
