//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_basi040
    {
        public string bga01 { get; set; }
        public string bga02 { get; set; }
        public string bga03 { get; set; }
        public Nullable<decimal> bga04 { get; set; }
        public string bga05 { get; set; }
        public string bga06 { get; set; }
        public string bgavali { get; set; }
        public string bgacreu { get; set; }
        public string bgacreg { get; set; }
        public Nullable<System.DateTime> bgacred { get; set; }
        public string bgamodu { get; set; }
        public string bgamodg { get; set; }
        public Nullable<System.DateTime> bgamodd { get; set; }
        public string bgasecu { get; set; }
        public string bgasecg { get; set; }
    }
}
