//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_basi040b
    {
        public string bgc01 { get; set; }
        public decimal bgc02 { get; set; }
        public string bgc03 { get; set; }
        public string bgc04 { get; set; }
        public string bgc05 { get; set; }
        public string bgc06 { get; set; }
        public string bgccreu { get; set; }
        public string bgccreg { get; set; }
        public Nullable<System.DateTime> bgccred { get; set; }
        public string bgcmodu { get; set; }
        public string bgcmodg { get; set; }
        public Nullable<System.DateTime> bgcmodd { get; set; }
    }
}
