//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_basi050
    {
        public string bef01 { get; set; }
        public string bef02 { get; set; }
        public string bef03 { get; set; }
        public string bef04 { get; set; }
        public string bef05 { get; set; }
        public string bef06 { get; set; }
        public string bef07 { get; set; }
        public string bef08 { get; set; }
        public string bef09 { get; set; }
        public string bef10 { get; set; }
        public string befvali { get; set; }
        public string befcreu { get; set; }
        public string befcreg { get; set; }
        public Nullable<System.DateTime> befcred { get; set; }
        public string befmodu { get; set; }
        public string befmodg { get; set; }
        public Nullable<System.DateTime> befmodd { get; set; }
        public string befsecu { get; set; }
        public string befsecg { get; set; }
    }
}
