//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_basi060
    {
        public string beg01 { get; set; }
        public string beg02 { get; set; }
        public Nullable<decimal> beg03 { get; set; }
        public string beg04 { get; set; }
        public string beg05 { get; set; }
        public string beg06 { get; set; }
        public string beg07 { get; set; }
        public string begvali { get; set; }
        public string begcreu { get; set; }
        public string begcreg { get; set; }
        public Nullable<System.DateTime> begcred { get; set; }
        public string begmodu { get; set; }
        public string begmodg { get; set; }
        public Nullable<System.DateTime> begmodd { get; set; }
        public string begsecu { get; set; }
        public string begsecg { get; set; }
    }
}
