//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_basi001
    {
        public string baacomp { get; set; }
        public string baa01 { get; set; }
        public string baa02 { get; set; }
        public string baa03 { get; set; }
        public string baa04 { get; set; }
        public Nullable<decimal> baa05 { get; set; }
        public Nullable<decimal> baa06 { get; set; }
        public string baa07 { get; set; }
        public Nullable<decimal> baa08 { get; set; }
        public string baa09 { get; set; }
        public string baa10 { get; set; }
        public string baa11 { get; set; }
        public string baa12 { get; set; }
        public string baa13 { get; set; }
        public string baa14 { get; set; }
        public string baa15 { get; set; }
        public string baa16 { get; set; }
        public string baa17 { get; set; }
        public string baa18 { get; set; }
        public string baa19 { get; set; }
        public string baa20 { get; set; }
        public string baacreu { get; set; }
        public string baacreg { get; set; }
        public Nullable<System.DateTime> baacred { get; set; }
        public string baamodu { get; set; }
        public string baamodg { get; set; }
        public Nullable<System.DateTime> baamodd { get; set; }
    }
}
