//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cari010
    {
        public string cac01 { get; set; }
        public string cac02 { get; set; }
        public string cac03 { get; set; }
        public string cac04 { get; set; }
        public string cac05 { get; set; }
        public string cac06 { get; set; }
        public string cac07 { get; set; }
        public string cac08 { get; set; }
        public string cac09 { get; set; }
        public string cac10 { get; set; }
        public string cac11 { get; set; }
        public string cac12 { get; set; }
        public string cac13 { get; set; }
        public string cac14 { get; set; }
        public string cac15 { get; set; }
        public string cac16 { get; set; }
        public string cac17 { get; set; }
        public string cac18 { get; set; }
        public string cac19 { get; set; }
        public string cac20 { get; set; }
        public string cacvali { get; set; }
        public string caccreu { get; set; }
        public string caccreg { get; set; }
        public Nullable<System.DateTime> caccred { get; set; }
        public string cacmodu { get; set; }
        public string cacmodg { get; set; }
        public Nullable<System.DateTime> cacmodd { get; set; }
        public string cacsecu { get; set; }
        public string cacsecg { get; set; }
        public string cac04_c { get; set; }
    }
}
