//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cari030
    {
        public string cba01 { get; set; }
        public string cba02 { get; set; }
        public string cba03 { get; set; }
        public string cba04 { get; set; }
        public string cba05 { get; set; }
        public string cba06 { get; set; }
        public string cba07 { get; set; }
        public string cba08 { get; set; }
        public string cba09 { get; set; }
        public string cba10 { get; set; }
        public string cba11 { get; set; }
        public string cba12 { get; set; }
        public string cba13 { get; set; }
        public string cba14 { get; set; }
        public string cba15 { get; set; }
        public string cba16 { get; set; }
        public string cba17 { get; set; }
        public string cba18 { get; set; }
        public string cba19 { get; set; }
        public string cba20 { get; set; }
        public string cbacreu { get; set; }
        public string cbacreg { get; set; }
        public Nullable<System.DateTime> cbacred { get; set; }
        public string cbamodu { get; set; }
        public string cbamodg { get; set; }
        public Nullable<System.DateTime> cbamodd { get; set; }
    }
}
