//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cart110
    {
        public string cee01 { get; set; }
        public string cee02 { get; set; }
        public Nullable<System.DateTime> cee03 { get; set; }
        public string cee04 { get; set; }
        public string cee05 { get; set; }
        public string cee06 { get; set; }
        public string cee07 { get; set; }
        public string cee08 { get; set; }
        public string cee09 { get; set; }
        public string cee10 { get; set; }
        public decimal cee11 { get; set; }
        public Nullable<decimal> cee12 { get; set; }
        public string cee13 { get; set; }
        public decimal cee14 { get; set; }
        public decimal cee14t { get; set; }
        public decimal cee14g { get; set; }
        public string cee15 { get; set; }
        public string cee16 { get; set; }
        public string cee17 { get; set; }
        public string cee18 { get; set; }
        public string cee19 { get; set; }
        public string cee20 { get; set; }
        public string cee21 { get; set; }
        public string cee22 { get; set; }
        public string cee23 { get; set; }
        public string cee24 { get; set; }
        public string cee25 { get; set; }
        public string cee26 { get; set; }
        public string cee27 { get; set; }
        public string cee28 { get; set; }
        public string cee29 { get; set; }
        public string cee30 { get; set; }
        public string ceecomp { get; set; }
        public string ceecreu { get; set; }
        public string ceecreg { get; set; }
        public Nullable<System.DateTime> ceecred { get; set; }
        public string ceemodu { get; set; }
        public string ceemodg { get; set; }
        public Nullable<System.DateTime> ceemodd { get; set; }
        public string ceesecu { get; set; }
        public string ceesecg { get; set; }
    }
}
