//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glai010
    {
        public string gac01 { get; set; }
        public string gac02 { get; set; }
        public string gac03 { get; set; }
        public string gac04 { get; set; }
        public string gac05 { get; set; }
        public string gac06 { get; set; }
        public string gac07 { get; set; }
        public string gac08 { get; set; }
        public string gac09 { get; set; }
        public string gac10 { get; set; }
        public string gac11 { get; set; }
        public string gac12 { get; set; }
        public string gac13 { get; set; }
        public string gac14 { get; set; }
        public string gac15 { get; set; }
        public string gac16 { get; set; }
        public string gac17 { get; set; }
        public string gac18 { get; set; }
        public string gac19 { get; set; }
        public string gac20 { get; set; }
        public string gacvali { get; set; }
        public string gaccreu { get; set; }
        public string gaccreg { get; set; }
        public Nullable<System.DateTime> gaccred { get; set; }
        public string gacmodu { get; set; }
        public string gacmodg { get; set; }
        public Nullable<System.DateTime> gacmodd { get; set; }
        public string gacsecu { get; set; }
        public string gacsecg { get; set; }
    }
}
