//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glat300s
    {
        public string gfb01 { get; set; }
        public decimal gfb02 { get; set; }
        public string gfb03 { get; set; }
        public string gfb04 { get; set; }
        public string gfb05 { get; set; }
        public string gfb06 { get; set; }
        public decimal gfb07 { get; set; }
        public string gfb08 { get; set; }
        public decimal gfb09 { get; set; }
        public decimal gfb10 { get; set; }
        public string gfb11 { get; set; }
        public string gfb12 { get; set; }
        public string gfb13 { get; set; }
        public string gfb14 { get; set; }
        public string gfb15 { get; set; }
        public string gfb16 { get; set; }
        public string gfb17 { get; set; }
        public string gfb18 { get; set; }
        public string gfb19 { get; set; }
        public string gfb20 { get; set; }
        public string gfbcomp { get; set; }
        public string gfbcreu { get; set; }
        public string gfbcreg { get; set; }
        public Nullable<System.DateTime> gfbcred { get; set; }
        public string gfbmodu { get; set; }
        public string gfbmodg { get; set; }
        public Nullable<System.DateTime> gfbmodd { get; set; }
        public string gfb03_c { get; set; }
        public string gba05 { get; set; }
        public string gba08 { get; set; }
        public string gba09 { get; set; }
    }
}
