//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glaq402s
    {
        public string gbi01 { get; set; }
        public System.DateTime gbi02 { get; set; }
        public decimal gbi03 { get; set; }
        public decimal gbi04 { get; set; }
        public decimal gbi05 { get; set; }
        public decimal gbi06 { get; set; }
        public string gbicomp { get; set; }
        public Nullable<decimal> sum_blance { get; set; }
    }
}
