//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glaq410s
    {
        public string gfh01 { get; set; }
        public decimal gfh02 { get; set; }
        public string gfh03 { get; set; }
        public decimal gfh04 { get; set; }
        public Nullable<System.DateTime> gfh05 { get; set; }
        public string gfh06 { get; set; }
        public string gfh07 { get; set; }
        public string gfh08 { get; set; }
        public decimal gfh09 { get; set; }
        public string gfh10 { get; set; }
        public string gfh11 { get; set; }
        public string gfh12 { get; set; }
        public string gfh13 { get; set; }
        public string gfh14 { get; set; }
        public string gfh15 { get; set; }
        public string gfhconf { get; set; }
        public string gfhcomp { get; set; }
    }
}
