//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glai100
    {
        public string gba01 { get; set; }
        public string gba02 { get; set; }
        public string gba03 { get; set; }
        public string gba04 { get; set; }
        public string gba05 { get; set; }
        public string gba06 { get; set; }
        public string gba07 { get; set; }
        public string gba08 { get; set; }
        public string gba09 { get; set; }
        public string gba10 { get; set; }
        public string gba11 { get; set; }
        public string gba12 { get; set; }
        public string gba13 { get; set; }
        public string gba14 { get; set; }
        public string gba15 { get; set; }
        public string gba16 { get; set; }
        public string gba17 { get; set; }
        public string gba18 { get; set; }
        public string gba19 { get; set; }
        public string gba20 { get; set; }
        public string gbavali { get; set; }
        public string gbacomp { get; set; }
        public string gbacreu { get; set; }
        public string gbacreg { get; set; }
        public Nullable<System.DateTime> gbacred { get; set; }
        public string gbamodu { get; set; }
        public string gbamodg { get; set; }
        public Nullable<System.DateTime> gbamodd { get; set; }
    }
}
