//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glaq410
    {
        public string gfg01 { get; set; }
        public decimal gfg02 { get; set; }
        public string gfg03 { get; set; }
        public string gfg04 { get; set; }
        public string gfg05 { get; set; }
        public Nullable<System.DateTime> gfg06 { get; set; }
        public decimal gfg07 { get; set; }
        public decimal gfg08 { get; set; }
        public decimal gfg09 { get; set; }
        public string gfg10 { get; set; }
        public string gfg11 { get; set; }
        public string gfg12 { get; set; }
        public string gfg13 { get; set; }
        public string gfg14 { get; set; }
        public string gfg15 { get; set; }
        public string gfgcomp { get; set; }
    }
}
