//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glai110s
    {
        public string gbd01 { get; set; }
        public string gbd02 { get; set; }
        public string gbd03 { get; set; }
        public string gbd04 { get; set; }
        public string gbd05 { get; set; }
        public string gbd06 { get; set; }
        public string gbd07 { get; set; }
        public string gbd08 { get; set; }
        public string gbdvali { get; set; }
        public string gbdcomp { get; set; }
        public string gbdcreu { get; set; }
        public string gbdcreg { get; set; }
        public Nullable<System.DateTime> gbdcred { get; set; }
        public string gbdmodu { get; set; }
        public string gbdmodg { get; set; }
        public Nullable<System.DateTime> gbdmodd { get; set; }
        public string gbd02_c { get; set; }
    }
}
