//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_glar311
    {
        public string gfa01 { get; set; }
        public Nullable<System.DateTime> gfa02_s { get; set; }
        public Nullable<System.DateTime> gfa02_e { get; set; }
        public string gfaconf { get; set; }
        public string gfapost { get; set; }
        public string gfb05 { get; set; }
        public string order1 { get; set; }
        public string order1_jump_yn { get; set; }
        public string order1_sum_yn { get; set; }
        public string order2 { get; set; }
        public string order2_jump_yn { get; set; }
        public string order2_sum_yn { get; set; }
        public string order3 { get; set; }
        public string order3_jump_yn { get; set; }
        public string order3_sum_yn { get; set; }
    }
}
