//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invt331
    {
        public string ifa00 { get; set; }
        public string ifa01 { get; set; }
        public Nullable<System.DateTime> ifa02 { get; set; }
        public string ifa03 { get; set; }
        public string ifa04 { get; set; }
        public string ifa05 { get; set; }
        public string ifa06 { get; set; }
        public Nullable<System.DateTime> ifa07 { get; set; }
        public string ifa08 { get; set; }
        public string ifa09 { get; set; }
        public Nullable<System.DateTime> ifa10 { get; set; }
        public string ifa11 { get; set; }
        public string ifa12 { get; set; }
        public string ifa13 { get; set; }
        public string ifa14 { get; set; }
        public string ifa15 { get; set; }
        public string ifaconf { get; set; }
        public Nullable<System.DateTime> ifacond { get; set; }
        public string ifaconu { get; set; }
        public string ifacomp { get; set; }
        public string ifacreu { get; set; }
        public string ifacreg { get; set; }
        public Nullable<System.DateTime> ifacred { get; set; }
        public string ifamodu { get; set; }
        public string ifamodg { get; set; }
        public Nullable<System.DateTime> ifamodd { get; set; }
        public string ifasecu { get; set; }
        public string ifasecg { get; set; }
        public string ifa03_c { get; set; }
        public string ifa04_c { get; set; }
        public string ifa01_c { get; set; }
        public string ifa06_c { get; set; }
        public string ifa08_c { get; set; }
    }
}
