//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invb501s
    {
        public string ipb01 { get; set; }
        public decimal ipb02 { get; set; }
        public string ipb03 { get; set; }
        public string ipb04 { get; set; }
        public string ipb05 { get; set; }
        public Nullable<decimal> ipb06 { get; set; }
        public string ipb07 { get; set; }
        public string ipb08 { get; set; }
        public string ipb09 { get; set; }
        public string ipb10 { get; set; }
        public string ipb11 { get; set; }
        public string ipb12 { get; set; }
        public string ipb13 { get; set; }
        public string ipb14 { get; set; }
        public string ipb15 { get; set; }
        public string ipb16 { get; set; }
        public Nullable<decimal> ipb30 { get; set; }
        public string ipb31 { get; set; }
        public Nullable<System.DateTime> ipb32 { get; set; }
        public Nullable<decimal> ipb40 { get; set; }
        public string ipb41 { get; set; }
        public Nullable<System.DateTime> ipb42 { get; set; }
        public Nullable<decimal> ipb50 { get; set; }
        public string ipb51 { get; set; }
        public Nullable<System.DateTime> ipb52 { get; set; }
        public string ipbcomp { get; set; }
        public string ipbcreu { get; set; }
        public string ipbcreg { get; set; }
        public Nullable<System.DateTime> ipbcred { get; set; }
        public string ipbmodu { get; set; }
        public string ipbmodg { get; set; }
        public Nullable<System.DateTime> ipbmodd { get; set; }
    }
}
