//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invq210s
    {
        public string icc01 { get; set; }
        public string icc02 { get; set; }
        public string icc03 { get; set; }
        public string icc04 { get; set; }
        public decimal icc05 { get; set; }
        public string icc06 { get; set; }
        public string icc07 { get; set; }
        public string icc08 { get; set; }
        public string icc09 { get; set; }
        public string icc10 { get; set; }
        public string icccomp { get; set; }
        public string icc02_c { get; set; }
    }
}
