//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi020
    {
        public string icm01 { get; set; }
        public string icm02 { get; set; }
        public decimal icm03 { get; set; }
        public decimal icm04 { get; set; }
        public string icm05 { get; set; }
        public string icm06 { get; set; }
        public string icm07 { get; set; }
        public string icm08 { get; set; }
        public string icmvali { get; set; }
        public string icmcreu { get; set; }
        public string icmcreg { get; set; }
        public Nullable<System.DateTime> icmcred { get; set; }
        public string icmmodu { get; set; }
        public string icmmodg { get; set; }
        public Nullable<System.DateTime> icmmodd { get; set; }
        public string icmsecu { get; set; }
        public string icmsecg { get; set; }
        public string icm01_c { get; set; }
        public string icm02_c { get; set; }
    }
}
