//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invq220
    {
        public string ina01 { get; set; }
        public decimal ina02 { get; set; }
        public string ina03 { get; set; }
        public string ina04 { get; set; }
        public string ina05 { get; set; }
        public string ina06 { get; set; }
        public decimal ina07 { get; set; }
        public string ina08 { get; set; }
        public decimal ina09 { get; set; }
        public decimal ina10 { get; set; }
        public string ina11 { get; set; }
        public string ina12 { get; set; }
        public Nullable<System.DateTime> ina13 { get; set; }
        public Nullable<System.DateTime> ina14 { get; set; }
        public string ina15 { get; set; }
        public string ina16 { get; set; }
        public string ina17 { get; set; }
        public string ina18 { get; set; }
        public string ina19 { get; set; }
        public string ina20 { get; set; }
        public string ina21 { get; set; }
        public string ina22 { get; set; }
        public string ina23 { get; set; }
        public string ina24 { get; set; }
        public string ina25 { get; set; }
        public string inacomp { get; set; }
        public string inacreu { get; set; }
        public string inacreg { get; set; }
        public Nullable<System.DateTime> inacred { get; set; }
        public string inamodu { get; set; }
        public string inamodg { get; set; }
        public Nullable<System.DateTime> inamodd { get; set; }
        public string inasecu { get; set; }
        public string inasecg { get; set; }
        public string ina01_c { get; set; }
        public string ina03_c { get; set; }
    }
}
