//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invb500
    {
        public string ipa01 { get; set; }
        public Nullable<System.DateTime> ipa02 { get; set; }
        public Nullable<System.DateTime> ipa03 { get; set; }
        public string ipa04 { get; set; }
        public string icc01 { get; set; }
        public string icc02 { get; set; }
        public string icc03 { get; set; }
        public string order_by_1 { get; set; }
        public string order_by_2 { get; set; }
        public string order_by_3 { get; set; }
    }
}
