//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invt330s
    {
        public string ifb01 { get; set; }
        public decimal ifb02 { get; set; }
        public string ifb03 { get; set; }
        public string ifb04 { get; set; }
        public decimal ifb05 { get; set; }
        public string ifb06 { get; set; }
        public string ifb07 { get; set; }
        public decimal ifb08 { get; set; }
        public string ifb09 { get; set; }
        public string ifb10 { get; set; }
        public string ifb11 { get; set; }
        public decimal ifb12 { get; set; }
        public decimal ifb13 { get; set; }
        public string ifb14 { get; set; }
        public string ifb15 { get; set; }
        public string ifb16 { get; set; }
        public string ifb17 { get; set; }
        public string ifb18 { get; set; }
        public string ifbcomp { get; set; }
        public string ifbcreu { get; set; }
        public string ifbcreg { get; set; }
        public Nullable<System.DateTime> ifbcred { get; set; }
        public string ifbmodu { get; set; }
        public string ifbmodg { get; set; }
        public Nullable<System.DateTime> ifbmodd { get; set; }
    }
}
