//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi100_2
    {
        public string pfa01 { get; set; }
        public Nullable<System.DateTime> pfa02 { get; set; }
        public string pfa03 { get; set; }
        public string pca03 { get; set; }
        public Nullable<decimal> pfb02 { get; set; }
        public string pfb03 { get; set; }
        public string pfb04 { get; set; }
        public Nullable<decimal> pfb05 { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_twd { get; set; }
        public string pfa10 { get; set; }
    }
}
