//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invt402
    {
        public string ima01 { get; set; }
        public Nullable<System.DateTime> ima02 { get; set; }
        public string ima03 { get; set; }
        public string ima04 { get; set; }
        public string ima05 { get; set; }
        public string ima06 { get; set; }
        public decimal ima07 { get; set; }
        public string ima08 { get; set; }
        public string ima09 { get; set; }
        public string ima10 { get; set; }
        public string ima11 { get; set; }
        public string ima12 { get; set; }
        public decimal ima13 { get; set; }
        public decimal ima13t { get; set; }
        public decimal ima13g { get; set; }
        public decimal ima14 { get; set; }
        public string ima15 { get; set; }
        public string ima16 { get; set; }
        public string ima17 { get; set; }
        public string ima18 { get; set; }
        public string ima19 { get; set; }
        public string ima20 { get; set; }
        public string imaconf { get; set; }
        public Nullable<System.DateTime> imacond { get; set; }
        public string imaconu { get; set; }
        public string imastat { get; set; }
        public string imacomp { get; set; }
        public string imacreu { get; set; }
        public string imacreg { get; set; }
        public Nullable<System.DateTime> imacred { get; set; }
        public string imamodu { get; set; }
        public string imamodg { get; set; }
        public Nullable<System.DateTime> imamodd { get; set; }
        public string imasecu { get; set; }
        public string imasecg { get; set; }
        public string ima03_c { get; set; }
        public string ima04_c { get; set; }
        public string ima05_c { get; set; }
        public string ima01_c { get; set; }
    }
}
