//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi200
    {
        public string icb01 { get; set; }
        public string icb02 { get; set; }
        public string icb03 { get; set; }
        public string icb04 { get; set; }
        public string icb05 { get; set; }
        public string icb06 { get; set; }
        public string icb07 { get; set; }
        public string icb08 { get; set; }
        public string icb09 { get; set; }
        public string icb10 { get; set; }
        public string icbvali { get; set; }
        public string icbcreu { get; set; }
        public string icbcreg { get; set; }
        public Nullable<System.DateTime> icbcred { get; set; }
        public string icbmodu { get; set; }
        public string icbmodg { get; set; }
        public Nullable<System.DateTime> icbmodd { get; set; }
        public string icbsecu { get; set; }
        public string icbsecg { get; set; }
    }
}
