//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invt302s
    {
        public string igb01 { get; set; }
        public decimal igb02 { get; set; }
        public string igb03 { get; set; }
        public string igb04 { get; set; }
        public decimal igb05 { get; set; }
        public string igb06 { get; set; }
        public decimal igb07 { get; set; }
        public decimal igb08 { get; set; }
        public string igb09 { get; set; }
        public string igb10 { get; set; }
        public string igb11 { get; set; }
        public decimal igb12 { get; set; }
        public decimal igb13 { get; set; }
        public string igb14 { get; set; }
        public string igb15 { get; set; }
        public string igb16 { get; set; }
        public string igb17 { get; set; }
        public string igb18 { get; set; }
        public string igb19 { get; set; }
        public string igb20 { get; set; }
        public string igbcomp { get; set; }
        public string igbcreu { get; set; }
        public string igbcreg { get; set; }
        public Nullable<System.DateTime> igbcred { get; set; }
        public string igbmodu { get; set; }
        public string igbmodg { get; set; }
        public Nullable<System.DateTime> igbmodd { get; set; }
        public string xc_igb001 { get; set; }
        public Nullable<decimal> xc_igb002 { get; set; }
    }
}
