//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invq210
    {
        public string ica01 { get; set; }
        public string ica02 { get; set; }
        public string ica03 { get; set; }
        public string ica04 { get; set; }
        public string ica05 { get; set; }
        public string ica06 { get; set; }
        public string ica04_c { get; set; }
        public string ica05_c { get; set; }
        public string ica06_c { get; set; }
        public string ica07 { get; set; }
    }
}
