//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi030
    {
        public string icx01 { get; set; }
        public string icx02 { get; set; }
        public string icx03 { get; set; }
        public string icx04 { get; set; }
        public string icx05 { get; set; }
        public string icxcreu { get; set; }
        public string icxcreg { get; set; }
        public Nullable<System.DateTime> icxcred { get; set; }
        public string icxmodu { get; set; }
        public string icxmodg { get; set; }
        public Nullable<System.DateTime> icxmodd { get; set; }
        public string icxsecu { get; set; }
        public string icxsecg { get; set; }
    }
}
