//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invb502
    {
        public string ipa01 { get; set; }
        public Nullable<System.DateTime> ipa02 { get; set; }
        public Nullable<System.DateTime> ipa03 { get; set; }
        public string ipa04 { get; set; }
        public string ipa05 { get; set; }
        public Nullable<System.DateTime> ipa06 { get; set; }
        public string ipa07 { get; set; }
        public Nullable<System.DateTime> ipa08 { get; set; }
        public string ipa09 { get; set; }
        public string ipa10 { get; set; }
        public string ipa11 { get; set; }
        public string ipa12 { get; set; }
        public string ipa13 { get; set; }
        public string ipa14 { get; set; }
        public string ipa15 { get; set; }
        public string ipa16 { get; set; }
        public string ipa17 { get; set; }
        public string ipa18 { get; set; }
        public string ipa19 { get; set; }
        public string ipavali { get; set; }
        public string ipacomp { get; set; }
        public string ipacreu { get; set; }
        public string ipacreg { get; set; }
        public Nullable<System.DateTime> ipacred { get; set; }
        public string ipamodu { get; set; }
        public string ipamodg { get; set; }
        public Nullable<System.DateTime> ipamodd { get; set; }
        public string ipasecu { get; set; }
        public string ipasecg { get; set; }
        public string ipa01_c { get; set; }
    }
}
