//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi100_1
    {
        public string pga01 { get; set; }
        public Nullable<System.DateTime> pga02 { get; set; }
        public string pga03 { get; set; }
        public string pca03 { get; set; }
        public Nullable<decimal> pgb02 { get; set; }
        public string pgb03 { get; set; }
        public string pgb04 { get; set; }
        public Nullable<decimal> pgb05 { get; set; }
        public Nullable<decimal> price { get; set; }
        public string pfa08 { get; set; }
        public string pfa10 { get; set; }
        public Nullable<decimal> pfa17 { get; set; }
        public Nullable<decimal> pfb09 { get; set; }
    }
}
