//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi103s
    {
        public string icd01 { get; set; }
        public string icd02 { get; set; }
        public string icd03 { get; set; }
        public string icd04 { get; set; }
        public string icd05 { get; set; }
        public string icd06 { get; set; }
        public string icd07 { get; set; }
        public string icd08 { get; set; }
        public string icd09 { get; set; }
        public string icd10 { get; set; }
    }
}
