//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invt401s
    {
        public string ilb01 { get; set; }
        public decimal ilb02 { get; set; }
        public string ilb03 { get; set; }
        public string ilb04 { get; set; }
        public decimal ilb05 { get; set; }
        public string ilb06 { get; set; }
        public string ilb07 { get; set; }
        public decimal ilb08 { get; set; }
        public decimal ilb09 { get; set; }
        public decimal ilb10 { get; set; }
        public decimal ilb10t { get; set; }
        public string ilb11 { get; set; }
        public string ilb12 { get; set; }
        public Nullable<System.DateTime> ilb13 { get; set; }
        public string ilb14 { get; set; }
        public decimal ilb15 { get; set; }
        public decimal ilb16 { get; set; }
        public decimal ilb17 { get; set; }
        public string ilb18 { get; set; }
        public string ilb19 { get; set; }
        public string ilb20 { get; set; }
        public string ilb21 { get; set; }
        public string ilb22 { get; set; }
        public string ilb23 { get; set; }
        public string ilb24 { get; set; }
        public string ilb25 { get; set; }
        public string ilbcomp { get; set; }
        public string ilbcreu { get; set; }
        public string ilbcreg { get; set; }
        public Nullable<System.DateTime> ilbcred { get; set; }
        public string ilbmodu { get; set; }
        public string ilbmodg { get; set; }
        public Nullable<System.DateTime> ilbmodd { get; set; }
    }
}
