//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi102
    {
        public string icp01 { get; set; }
        public decimal icp02 { get; set; }
        public byte[] icp03 { get; set; }
        public string icp04 { get; set; }
        public Nullable<decimal> icp05 { get; set; }
        public string icp06 { get; set; }
        public string icp07 { get; set; }
        public string icp08 { get; set; }
        public string icpcreu { get; set; }
        public string icpcreg { get; set; }
        public Nullable<System.DateTime> icpcred { get; set; }
        public string icpmodu { get; set; }
        public string icpmodg { get; set; }
        public Nullable<System.DateTime> icpmodd { get; set; }
        public string icp01_c { get; set; }
    }
}
