//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi010
    {
        public string bab01 { get; set; }
        public string bab02 { get; set; }
        public string bab03 { get; set; }
        public string bab04 { get; set; }
        public string bab05 { get; set; }
        public string bab06 { get; set; }
        public string bab07 { get; set; }
        public string bab08 { get; set; }
        public string bab09 { get; set; }
        public string bab10 { get; set; }
        public string bab11 { get; set; }
        public string bab12 { get; set; }
        public string bab13 { get; set; }
        public string bab14 { get; set; }
        public string bab15 { get; set; }
        public string bab16 { get; set; }
        public string bab17 { get; set; }
        public string bab18 { get; set; }
        public string bab19 { get; set; }
        public string bab20 { get; set; }
        public string babvali { get; set; }
        public string babcreu { get; set; }
        public string babcreg { get; set; }
        public Nullable<System.DateTime> babcred { get; set; }
        public string babmodu { get; set; }
        public string babmodg { get; set; }
        public Nullable<System.DateTime> babmodd { get; set; }
        public string babsecu { get; set; }
        public string babsecg { get; set; }
        public string bab04_c { get; set; }
    }
}
