//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invi101s
    {
        public string icn01 { get; set; }
        public string icn02 { get; set; }
        public string icn03 { get; set; }
        public decimal icn04 { get; set; }
        public decimal icn05 { get; set; }
        public string icn06 { get; set; }
        public string icn07 { get; set; }
        public string icn08 { get; set; }
        public string icnvali { get; set; }
        public string icncreu { get; set; }
        public string icncreg { get; set; }
        public Nullable<System.DateTime> icncred { get; set; }
        public string icnmodu { get; set; }
        public string icnmodg { get; set; }
        public Nullable<System.DateTime> icnmodd { get; set; }
    }
}
