//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mant412s
    {
        public string mib01 { get; set; }
        public decimal mib02 { get; set; }
        public string mib03 { get; set; }
        public string mib04 { get; set; }
        public decimal mib05 { get; set; }
        public string mib06 { get; set; }
        public string mib07 { get; set; }
        public string mib08 { get; set; }
        public decimal mib09 { get; set; }
        public decimal mib10 { get; set; }
        public decimal mib10t { get; set; }
        public string mib11 { get; set; }
        public string mib12 { get; set; }
        public string mib13 { get; set; }
        public string mib14 { get; set; }
        public string mib15 { get; set; }
        public string mib16 { get; set; }
        public string mib17 { get; set; }
        public string mib18 { get; set; }
        public string mib19 { get; set; }
        public string mib20 { get; set; }
        public string mibcomp { get; set; }
        public string mibcreu { get; set; }
        public string mibcreg { get; set; }
        public Nullable<System.DateTime> mibcred { get; set; }
        public string mibmodu { get; set; }
        public string mibmodg { get; set; }
        public Nullable<System.DateTime> mibmodd { get; set; }
    }
}
