//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mant210s
    {
        public string meb01 { get; set; }
        public decimal meb02 { get; set; }
        public string meb03 { get; set; }
        public string meb04 { get; set; }
        public decimal meb05 { get; set; }
        public string meb06 { get; set; }
        public string meb07 { get; set; }
        public decimal meb08 { get; set; }
        public decimal meb09 { get; set; }
        public string meb10 { get; set; }
        public string meb11 { get; set; }
        public string meb12 { get; set; }
        public string meb13 { get; set; }
        public string meb14 { get; set; }
        public string meb15 { get; set; }
        public string meb16 { get; set; }
        public string meb17 { get; set; }
        public string meb18 { get; set; }
        public string meb19 { get; set; }
        public string meb20 { get; set; }
        public string mebcomp { get; set; }
        public string mebcreu { get; set; }
        public string mebcreg { get; set; }
        public Nullable<System.DateTime> mebcred { get; set; }
        public string mebmodu { get; set; }
        public string mebmodg { get; set; }
        public Nullable<System.DateTime> mebmodd { get; set; }
    }
}
