//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mant411
    {
        public string mha00 { get; set; }
        public string mha01 { get; set; }
        public Nullable<System.DateTime> mha02 { get; set; }
        public string mha03 { get; set; }
        public string mha04 { get; set; }
        public string mha05 { get; set; }
        public string mha06 { get; set; }
        public decimal mha07 { get; set; }
        public string mha08 { get; set; }
        public string mha09 { get; set; }
        public string mha10 { get; set; }
        public string mha11 { get; set; }
        public string mha12 { get; set; }
        public decimal mha13 { get; set; }
        public decimal mha13t { get; set; }
        public decimal mha13g { get; set; }
        public string mha14 { get; set; }
        public string mha15 { get; set; }
        public string mha16 { get; set; }
        public string mha17 { get; set; }
        public string mha18 { get; set; }
        public string mha19 { get; set; }
        public string mha20 { get; set; }
        public string mhaconf { get; set; }
        public string mhaconu { get; set; }
        public Nullable<System.DateTime> mhacond { get; set; }
        public string mhacomp { get; set; }
        public string mhacreu { get; set; }
        public string mhacreg { get; set; }
        public Nullable<System.DateTime> mhacred { get; set; }
        public string mhamodu { get; set; }
        public string mhamodg { get; set; }
        public Nullable<System.DateTime> mhamodd { get; set; }
        public string mhasecu { get; set; }
        public string mhasecg { get; set; }
        public string mha03_c { get; set; }
        public string mha04_c { get; set; }
        public string mha05_c { get; set; }
        public string mha11_c { get; set; }
        public string mha01_c { get; set; }
    }
}
