//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mant210_1
    {
        public Nullable<int> level { get; set; }
        public string mea01 { get; set; }
        public string keySelf { get; set; }
        public string keyParents { get; set; }
        public string mea20 { get; set; }
        public string mea21 { get; set; }
        public decimal mea22 { get; set; }
        public string mea23 { get; set; }
        public decimal mea26 { get; set; }
        public decimal mea27 { get; set; }
    }
}
