//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mant311
    {
        public string mfa00 { get; set; }
        public string mfa01 { get; set; }
        public Nullable<System.DateTime> mfa02 { get; set; }
        public string mfa03 { get; set; }
        public string mfa04 { get; set; }
        public string mfa05 { get; set; }
        public string mfa06 { get; set; }
        public string mfa07 { get; set; }
        public string mfa08 { get; set; }
        public string mfa09 { get; set; }
        public string mfa10 { get; set; }
        public string mfa11 { get; set; }
        public string mfa12 { get; set; }
        public string mfa13 { get; set; }
        public string mfa14 { get; set; }
        public string mfa15 { get; set; }
        public string mfaconf { get; set; }
        public string mfaconu { get; set; }
        public Nullable<System.DateTime> mfacond { get; set; }
        public string mfacomp { get; set; }
        public string mfacreu { get; set; }
        public string mfacreg { get; set; }
        public Nullable<System.DateTime> mfacred { get; set; }
        public string mfamodu { get; set; }
        public string mfamodg { get; set; }
        public Nullable<System.DateTime> mfamodd { get; set; }
        public string mfasecu { get; set; }
        public string mfasecg { get; set; }
        public string mfa03_c { get; set; }
        public string mfa04_c { get; set; }
        public string mfa05_c { get; set; }
        public string mfa01_c { get; set; }
    }
}
