//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_purt500
    {
        public string pha01 { get; set; }
        public Nullable<System.DateTime> pha02 { get; set; }
        public string pha03 { get; set; }
        public string pha04 { get; set; }
        public string pha05 { get; set; }
        public string pha06 { get; set; }
        public decimal pha07 { get; set; }
        public string pha08 { get; set; }
        public string pha09 { get; set; }
        public string pha10 { get; set; }
        public string pha11 { get; set; }
        public string pha12 { get; set; }
        public decimal pha13 { get; set; }
        public decimal pha13t { get; set; }
        public decimal pha13g { get; set; }
        public decimal pha14 { get; set; }
        public string pha15 { get; set; }
        public string pha16 { get; set; }
        public string pha17 { get; set; }
        public string pha18 { get; set; }
        public string pha19 { get; set; }
        public string pha20 { get; set; }
        public string phaconf { get; set; }
        public Nullable<System.DateTime> phacond { get; set; }
        public string phaconu { get; set; }
        public string phacomp { get; set; }
        public string phacreu { get; set; }
        public string phacreg { get; set; }
        public Nullable<System.DateTime> phacred { get; set; }
        public string phamodu { get; set; }
        public string phamodg { get; set; }
        public Nullable<System.DateTime> phamodd { get; set; }
        public string phasecu { get; set; }
        public string phasecg { get; set; }
        public string pha03_c { get; set; }
        public string pha04_c { get; set; }
        public string pha05_c { get; set; }
        public string pha01_c { get; set; }
    }
}
