//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_purt200s
    {
        public string peb01 { get; set; }
        public decimal peb02 { get; set; }
        public string peb03 { get; set; }
        public string peb04 { get; set; }
        public decimal peb05 { get; set; }
        public string peb06 { get; set; }
        public string peb07 { get; set; }
        public decimal peb08 { get; set; }
        public decimal peb09 { get; set; }
        public decimal peb10 { get; set; }
        public decimal peb10t { get; set; }
        public decimal peb11 { get; set; }
        public string peb12 { get; set; }
        public string peb13 { get; set; }
        public string peb14 { get; set; }
        public string peb15 { get; set; }
        public string peb16 { get; set; }
        public string pebcomp { get; set; }
        public string pebcreu { get; set; }
        public string pebcreg { get; set; }
        public Nullable<System.DateTime> pebcred { get; set; }
        public string pebmodu { get; set; }
        public string pebmodg { get; set; }
        public Nullable<System.DateTime> pebmodd { get; set; }
        public string ica31 { get; set; }
    }
}
