//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_puri031
    {
        public string ica01 { get; set; }
        public string ica02 { get; set; }
        public string ica03 { get; set; }
        public string ica07 { get; set; }
        public string ica09 { get; set; }
        public decimal ica18 { get; set; }
        public decimal ica19 { get; set; }
        public Nullable<System.DateTime> ica20 { get; set; }
    }
}
