//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_puri100s
    {
        public string pcb01 { get; set; }
        public string pcb02 { get; set; }
        public string pcb03 { get; set; }
        public string pcb04 { get; set; }
        public string pcb05 { get; set; }
        public string pcb06 { get; set; }
        public string pcb07 { get; set; }
        public string pcb08 { get; set; }
        public string pcb09 { get; set; }
        public string pcb10 { get; set; }
        public string pcb11 { get; set; }
        public string pcb12 { get; set; }
        public string pcb13 { get; set; }
        public string pcbcreu { get; set; }
        public string pcbcreg { get; set; }
        public Nullable<System.DateTime> pcbcred { get; set; }
        public string pcbmodu { get; set; }
        public string pcbmodg { get; set; }
        public Nullable<System.DateTime> pcbmodd { get; set; }
    }
}
