//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_puri031s
    {
        public string pdd01 { get; set; }
        public string pdd02 { get; set; }
        public string pdd03 { get; set; }
        public decimal pdd04 { get; set; }
        public Nullable<System.DateTime> pdd05 { get; set; }
        public string pdd06 { get; set; }
        public decimal pdd07 { get; set; }
        public string pdd08 { get; set; }
        public decimal pdd09 { get; set; }
        public decimal pdd10 { get; set; }
        public decimal pdd11 { get; set; }
        public string pdd12 { get; set; }
        public string pdd13 { get; set; }
        public string pdd14 { get; set; }
        public string pdd15 { get; set; }
        public string pdd16 { get; set; }
        public string pdd17 { get; set; }
        public string pdd18 { get; set; }
        public string pdd19 { get; set; }
        public string pdd20 { get; set; }
        public string pddcreu { get; set; }
        public string pddcreg { get; set; }
        public Nullable<System.DateTime> pddcred { get; set; }
        public string pddmodu { get; set; }
        public string pddmodg { get; set; }
        public Nullable<System.DateTime> pddmodd { get; set; }
        public string pddsecu { get; set; }
        public string pddsecg { get; set; }
        public string pdd02_c { get; set; }
    }
}
