//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_puri020
    {
        public string pba01 { get; set; }
        public string pba02 { get; set; }
        public string pba03 { get; set; }
        public string pba04 { get; set; }
        public string pba05 { get; set; }
        public string pbavali { get; set; }
        public string pbacreu { get; set; }
        public string pbacreg { get; set; }
        public Nullable<System.DateTime> pbacred { get; set; }
        public string pbamodu { get; set; }
        public string pbamodg { get; set; }
        public Nullable<System.DateTime> pbamodd { get; set; }
        public string pbasecu { get; set; }
        public string pbasecg { get; set; }
    }
}
