//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpt400
    {
        public string sga01 { get; set; }
        public Nullable<System.DateTime> sga02 { get; set; }
        public string sga03 { get; set; }
        public string sga04 { get; set; }
        public string sga05 { get; set; }
        public string sga06 { get; set; }
        public decimal sga07 { get; set; }
        public string sga08 { get; set; }
        public string sga09 { get; set; }
        public string sga10 { get; set; }
        public string sga11 { get; set; }
        public string sga12 { get; set; }
        public decimal sga13 { get; set; }
        public decimal sga13t { get; set; }
        public decimal sga13g { get; set; }
        public string sga14 { get; set; }
        public string sga15 { get; set; }
        public string sga16 { get; set; }
        public string sga17 { get; set; }
        public string sga18 { get; set; }
        public string sga19 { get; set; }
        public string sga20 { get; set; }
        public decimal sga21 { get; set; }
        public string sga22 { get; set; }
        public decimal sga23 { get; set; }
        public string sga24 { get; set; }
        public Nullable<System.DateTime> sga25 { get; set; }
        public string sga26 { get; set; }
        public string sga27 { get; set; }
        public string sga28 { get; set; }
        public string sga29 { get; set; }
        public string sga30 { get; set; }
        public string sga31 { get; set; }
        public string sga32 { get; set; }
        public string sga33 { get; set; }
        public string sga34 { get; set; }
        public string sga35 { get; set; }
        public string sga36 { get; set; }
        public string sga37 { get; set; }
        public string sga38 { get; set; }
        public string sga39 { get; set; }
        public string sga40 { get; set; }
        public string sga41 { get; set; }
        public string sga42 { get; set; }
        public string sga43 { get; set; }
        public string sga44 { get; set; }
        public string sga45 { get; set; }
        public string sga46 { get; set; }
        public string sga47 { get; set; }
        public string sga48 { get; set; }
        public string sga49 { get; set; }
        public string sga50 { get; set; }
        public string sga51 { get; set; }
        public string sga52 { get; set; }
        public string sga53 { get; set; }
        public string sga54 { get; set; }
        public string sga55 { get; set; }
        public string sga56 { get; set; }
        public string sga57 { get; set; }
        public string sga58 { get; set; }
        public string sgaconf { get; set; }
        public Nullable<System.DateTime> sgacond { get; set; }
        public string sgaconu { get; set; }
        public string sgastat { get; set; }
        public string sgacomp { get; set; }
        public string sgacreu { get; set; }
        public string sgacreg { get; set; }
        public Nullable<System.DateTime> sgacred { get; set; }
        public string sgamodu { get; set; }
        public string sgamodg { get; set; }
        public Nullable<System.DateTime> sgamodd { get; set; }
        public string sgasecu { get; set; }
        public string sgasecg { get; set; }
        public Nullable<decimal> jja24 { get; set; }
        public string sga03_c { get; set; }
        public string sga04_c { get; set; }
        public string sga05_c { get; set; }
        public string sga11_c { get; set; }
        public string sga12_c { get; set; }
        public string sga01_c { get; set; }
        public string sga14_c { get; set; }
        public string sga15_c { get; set; }
        public string sga16_c { get; set; }
    }
}
