//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpt200s
    {
        public string seb01 { get; set; }
        public decimal seb02 { get; set; }
        public string seb03 { get; set; }
        public string seb04 { get; set; }
        public decimal seb05 { get; set; }
        public string seb06 { get; set; }
        public string seb07 { get; set; }
        public decimal seb08 { get; set; }
        public decimal seb09 { get; set; }
        public decimal seb10 { get; set; }
        public decimal seb10t { get; set; }
        public string seb11 { get; set; }
        public string seb12 { get; set; }
        public string seb13 { get; set; }
        public string seb14 { get; set; }
        public string seb15 { get; set; }
        public string seb16 { get; set; }
        public string seb17 { get; set; }
        public string sebcomp { get; set; }
        public string sebcreu { get; set; }
        public string sebcreg { get; set; }
        public Nullable<System.DateTime> sebcred { get; set; }
        public string sebmodu { get; set; }
        public string sebmodg { get; set; }
        public Nullable<System.DateTime> sebmodd { get; set; }
    }
}
