//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpt200
    {
        public string sea01 { get; set; }
        public Nullable<System.DateTime> sea02 { get; set; }
        public string sea03 { get; set; }
        public string sea04 { get; set; }
        public string sea05 { get; set; }
        public string sea06 { get; set; }
        public decimal sea07 { get; set; }
        public string sea08 { get; set; }
        public string sea09 { get; set; }
        public string sea10 { get; set; }
        public string sea11 { get; set; }
        public string sea12 { get; set; }
        public decimal sea13 { get; set; }
        public decimal sea13t { get; set; }
        public decimal sea13g { get; set; }
        public string sea14 { get; set; }
        public string sea15 { get; set; }
        public string sea16 { get; set; }
        public string sea17 { get; set; }
        public decimal sea18 { get; set; }
        public string sea19 { get; set; }
        public string sea20 { get; set; }
        public string sea21 { get; set; }
        public string sea22 { get; set; }
        public string sea23 { get; set; }
        public string sea24 { get; set; }
        public string seaconf { get; set; }
        public Nullable<System.DateTime> seacond { get; set; }
        public string seaconu { get; set; }
        public string seastat { get; set; }
        public string seacomp { get; set; }
        public string seacreu { get; set; }
        public string seacreg { get; set; }
        public Nullable<System.DateTime> seacred { get; set; }
        public string seamodu { get; set; }
        public string seamodg { get; set; }
        public Nullable<System.DateTime> seamodd { get; set; }
        public string seasecu { get; set; }
        public string seasecg { get; set; }
        public string sea03_c { get; set; }
        public string sea04_c { get; set; }
        public string sea05_c { get; set; }
        public string sea11_c { get; set; }
        public string sea12_c { get; set; }
        public string sea01_c { get; set; }
        public string sea14_c { get; set; }
        public string sea15_c { get; set; }
        public string sea16_c { get; set; }
    }
}
