//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpi100s
    {
        public string scb01 { get; set; }
        public string scb02 { get; set; }
        public string scb03 { get; set; }
        public string scb04 { get; set; }
        public string scb05 { get; set; }
        public string scb06 { get; set; }
        public string scb07 { get; set; }
        public string scb08 { get; set; }
        public string scb09 { get; set; }
        public string scb10 { get; set; }
        public string scb11 { get; set; }
        public string scb12 { get; set; }
        public string scbcreu { get; set; }
        public string scbcreg { get; set; }
        public Nullable<System.DateTime> scbcred { get; set; }
        public string scbmodu { get; set; }
        public string scbmodg { get; set; }
        public Nullable<System.DateTime> scbmodd { get; set; }
    }
}
