//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpt410s
    {
        public string sgb01 { get; set; }
        public decimal sgb02 { get; set; }
        public string sgb03 { get; set; }
        public string sgb04 { get; set; }
        public decimal sgb05 { get; set; }
        public string sgb06 { get; set; }
        public string sgb07 { get; set; }
        public decimal sgb08 { get; set; }
        public decimal sgb09 { get; set; }
        public decimal sgb10 { get; set; }
        public decimal sgb10t { get; set; }
        public string sgb11 { get; set; }
        public Nullable<decimal> sgb12 { get; set; }
        public decimal sgb13 { get; set; }
        public decimal sgb14 { get; set; }
        public string sgb15 { get; set; }
        public string sgb16 { get; set; }
        public decimal sgb17 { get; set; }
        public decimal sgb18 { get; set; }
        public decimal sgb19 { get; set; }
        public string sgb20 { get; set; }
        public string sgb21 { get; set; }
        public string sgb22 { get; set; }
        public string sgb23 { get; set; }
        public string sgb24 { get; set; }
        public string sgb25 { get; set; }
        public string sgb26 { get; set; }
        public string sgb27 { get; set; }
        public string sgb28 { get; set; }
        public string sgb29 { get; set; }
        public string sgb30 { get; set; }
        public string sgb31 { get; set; }
        public string sgb32 { get; set; }
        public string sgb33 { get; set; }
        public string sgb34 { get; set; }
        public string sgb35 { get; set; }
        public string sgb36 { get; set; }
        public string sgb37 { get; set; }
        public string sgb38 { get; set; }
        public string sgb39 { get; set; }
        public string sgb40 { get; set; }
        public string sgbcomp { get; set; }
        public string sgbcreu { get; set; }
        public string sgbcreg { get; set; }
        public Nullable<System.DateTime> sgbcred { get; set; }
        public string sgbmodu { get; set; }
        public string sgbmodg { get; set; }
        public Nullable<System.DateTime> sgbmodd { get; set; }
        public Nullable<long> stock_qty { get; set; }
        public string print_label { get; set; }
        public Nullable<decimal> ica18 { get; set; }
    }
}
