//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpi100
    {
        public string sca01 { get; set; }
        public string sca02 { get; set; }
        public string sca03 { get; set; }
        public string sca04 { get; set; }
        public string sca05 { get; set; }
        public string sca06 { get; set; }
        public string sca07 { get; set; }
        public string sca08 { get; set; }
        public string sca09 { get; set; }
        public string sca10 { get; set; }
        public string sca11 { get; set; }
        public string sca12 { get; set; }
        public Nullable<decimal> sca13 { get; set; }
        public Nullable<decimal> sca14 { get; set; }
        public Nullable<decimal> sca15 { get; set; }
        public string sca16 { get; set; }
        public string sca17 { get; set; }
        public string sca18 { get; set; }
        public string sca19 { get; set; }
        public string sca20 { get; set; }
        public string sca21 { get; set; }
        public string sca22 { get; set; }
        public string sca23 { get; set; }
        public string sca24 { get; set; }
        public string sca25 { get; set; }
        public string sca26 { get; set; }
        public string sca27 { get; set; }
        public string sca28 { get; set; }
        public string sca29 { get; set; }
        public string sca30 { get; set; }
        public string sca31 { get; set; }
        public string sca32 { get; set; }
        public string sca33 { get; set; }
        public string sca34 { get; set; }
        public string sca35 { get; set; }
        public string sca36 { get; set; }
        public string sca37 { get; set; }
        public string sca38 { get; set; }
        public string sca39 { get; set; }
        public string sca40 { get; set; }
        public string scaconf { get; set; }
        public string scavali { get; set; }
        public string scacreu { get; set; }
        public string scacreg { get; set; }
        public Nullable<System.DateTime> scacred { get; set; }
        public string scamodu { get; set; }
        public string scamodg { get; set; }
        public Nullable<System.DateTime> scamodd { get; set; }
        public string scasecu { get; set; }
        public string scasecg { get; set; }
        public string sca05_c { get; set; }
        public string sca21_c { get; set; }
        public string sca24_c { get; set; }
        public string sca25_c { get; set; }
        public string sca26_c { get; set; }
        public string sca27_c { get; set; }
    }
}
