//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpi031s
    {
        public string sdd01 { get; set; }
        public string sdd02 { get; set; }
        public string sdd03 { get; set; }
        public Nullable<System.DateTime> sdd04 { get; set; }
        public string sdd05 { get; set; }
        public string sdd06 { get; set; }
        public decimal sdd07 { get; set; }
        public string sdd08 { get; set; }
        public decimal sdd09 { get; set; }
        public decimal sdd10 { get; set; }
        public decimal sdd11 { get; set; }
        public string sdd12 { get; set; }
        public string sdd13 { get; set; }
        public string sdd14 { get; set; }
        public string sdd15 { get; set; }
        public string sdd16 { get; set; }
        public string sdd17 { get; set; }
        public string sdd18 { get; set; }
        public string sdd19 { get; set; }
        public string sdd20 { get; set; }
        public string sddcreu { get; set; }
        public string sddcreg { get; set; }
        public Nullable<System.DateTime> sddcred { get; set; }
        public string sddmodu { get; set; }
        public string sddmodg { get; set; }
        public Nullable<System.DateTime> sddmodd { get; set; }
        public string sddsecu { get; set; }
        public string sddsecg { get; set; }
        public string sdd02_c { get; set; }
    }
}
