//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpi030s
    {
        public string sbc01 { get; set; }
        public decimal sbc02 { get; set; }
        public string sbc03 { get; set; }
        public decimal sbc04 { get; set; }
        public string sbc05 { get; set; }
        public string sbc06 { get; set; }
        public string sbccreu { get; set; }
        public string sbccreg { get; set; }
        public Nullable<System.DateTime> sbccred { get; set; }
        public string sbcmodu { get; set; }
        public string sbcmodg { get; set; }
        public Nullable<System.DateTime> sbcmodd { get; set; }
        public string sbcsecu { get; set; }
        public string sbcsecg { get; set; }
    }
}
