//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stpt500s
    {
        public string shb01 { get; set; }
        public decimal shb02 { get; set; }
        public string shb03 { get; set; }
        public string shb04 { get; set; }
        public decimal shb05 { get; set; }
        public string shb06 { get; set; }
        public string shb07 { get; set; }
        public decimal shb08 { get; set; }
        public decimal shb09 { get; set; }
        public decimal shb10 { get; set; }
        public decimal shb10t { get; set; }
        public string shb11 { get; set; }
        public Nullable<decimal> shb12 { get; set; }
        public decimal shb13 { get; set; }
        public decimal shb14 { get; set; }
        public string shb15 { get; set; }
        public string shb16 { get; set; }
        public string shb17 { get; set; }
        public decimal shb18 { get; set; }
        public string shb19 { get; set; }
        public Nullable<System.DateTime> shb20 { get; set; }
        public string shb21 { get; set; }
        public string shb22 { get; set; }
        public string shb23 { get; set; }
        public string shb24 { get; set; }
        public string shb25 { get; set; }
        public string shb26 { get; set; }
        public string shb27 { get; set; }
        public string shbcomp { get; set; }
        public string shbcreu { get; set; }
        public string shbcreg { get; set; }
        public Nullable<System.DateTime> shbcred { get; set; }
        public string shbmodu { get; set; }
        public string shbmodg { get; set; }
        public Nullable<System.DateTime> shbmodd { get; set; }
    }
}
