//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_taxi020s
    {
        public decimal tbe01 { get; set; }
        public decimal tbe02 { get; set; }
        public decimal tbe03 { get; set; }
        public string tbe04 { get; set; }
        public string tbe05 { get; set; }
        public decimal tbe06 { get; set; }
        public string tbe07 { get; set; }
        public string tbe08 { get; set; }
        public string tbe09 { get; set; }
        public Nullable<System.DateTime> tbe10 { get; set; }
        public string tbe11 { get; set; }
        public string tbe12 { get; set; }
        public string tbe13 { get; set; }
        public string tbe14 { get; set; }
        public string tbe15 { get; set; }
        public string tbe16 { get; set; }
        public string tbe17 { get; set; }
        public string tbe18 { get; set; }
        public string tbe19 { get; set; }
        public string tbe20 { get; set; }
        public string tbecreu { get; set; }
        public string tbecreg { get; set; }
        public Nullable<System.DateTime> tbecred { get; set; }
        public string tbemodu { get; set; }
        public string tbemodg { get; set; }
        public Nullable<System.DateTime> tbemodd { get; set; }
        public Nullable<decimal> total_cnts { get; set; }
    }
}
