//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR.ERP.DAL.YRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zinvt001
    {
        public string iga00 { get; set; }
        public string iga01 { get; set; }
        public Nullable<System.DateTime> iga02 { get; set; }
        public string iga03 { get; set; }
        public string iga04 { get; set; }
        public string iga05 { get; set; }
        public string iga06 { get; set; }
        public string iga07 { get; set; }
        public string iga08 { get; set; }
        public string iga09 { get; set; }
        public string iga10 { get; set; }
        public string igaconf { get; set; }
        public Nullable<System.DateTime> igacond { get; set; }
        public string igaconu { get; set; }
        public string igacomp { get; set; }
        public string igacreu { get; set; }
        public string igacreg { get; set; }
        public Nullable<System.DateTime> igacred { get; set; }
        public string igamodu { get; set; }
        public string igamodg { get; set; }
        public Nullable<System.DateTime> igamodd { get; set; }
        public string igasecu { get; set; }
        public string igasecg { get; set; }
        public string iga03_c { get; set; }
        public string iga04_c { get; set; }
        public string iga01_c { get; set; }
    }
}
